/*
 *  This file is part of CoCalc: Copyright © 2026 Sagemath, Inc.
 *  License: MS-RSL – see LICENSE.md for details
 */

// The reference model and the seeded operation generator for the multibay
// fuzzer (see src/.agents/multibay-fuzzing-plan-2026-10-05.md). Pure: no
// cluster, no I/O, so it is unit-tested on its own (model.test.mjs).
//
// The model holds what the cluster must look like: accounts and their home
// bays, and projects with their owning bay, title and members. It changes
// only through operations that succeeded. Each generated operation carries
// the expected outcome where the permission rule is unambiguous ("ok" or
// "fail"); otherwise "either", and the model follows what happened.

export const VISIBLE_GROUPS = new Set(["owner", "collaborator", "viewer"]);

/** mulberry32: small, fast, seedable. */
export function makeRng(seed) {
  let a = seed >>> 0;
  const next = () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  return {
    next,
    int: (lo, hi) => lo + Math.floor(next() * (hi - lo + 1)),
    pick: (items) => items[Math.floor(next() * items.length)],
    chance: (p) => next() < p,
  };
}

export class Model {
  constructor() {
    /** account_id -> { account_id, home_bay_id, name } */
    this.accounts = new Map();
    /** project_id -> { project_id, owning_bay_id, title, users: {id: group} } */
    this.projects = new Map();
    /**
     * project_id -> fields whose value is unknown because an operation on
     * them failed in a way that may or may not have applied (during a fault).
     * The checker adopts the owning bay's value for these.
     */
    this.uncertain = new Map();
  }

  addAccount(account) {
    this.accounts.set(account.account_id, { ...account });
  }

  group(project_id, account_id) {
    return this.projects.get(project_id)?.users[account_id] ?? null;
  }

  members(project_id) {
    return Object.keys(this.projects.get(project_id)?.users ?? {});
  }

  markUncertain(project_id, field) {
    const fields = this.uncertain.get(project_id) ?? new Set();
    fields.add(field);
    this.uncertain.set(project_id, fields);
  }

  /** Apply a successful operation. */
  apply(op, result) {
    switch (op.kind) {
      case "create": {
        const home = this.accounts.get(op.actor).home_bay_id;
        this.projects.set(result.project_id, {
          project_id: result.project_id,
          owning_bay_id: home,
          title: op.title,
          users: { [op.actor]: "owner" },
        });
        return;
      }
      case "invite":
        this.projects.get(op.project_id).users[op.target] = "collaborator";
        return;
      case "rename":
        this.projects.get(op.project_id).title = op.title;
        return;
      case "set-role":
        this.projects.get(op.project_id).users[op.target] = op.role;
        return;
      case "remove":
        delete this.projects.get(op.project_id).users[op.target];
        return;
      case "transfer": {
        const users = this.projects.get(op.project_id).users;
        users[op.target] = "owner";
        users[op.actor] = "collaborator";
        return;
      }
    }
  }

  /** The fields an operation writes, for uncertainty tracking. */
  static fields(op) {
    switch (op.kind) {
      case "rename":
        return ["title"];
      case "invite":
      case "set-role":
      case "remove":
      case "transfer":
        return ["users"];
      default:
        return [];
    }
  }

  /** What `account_id` must see in its project list. */
  expectedList(account_id) {
    const rows = new Map();
    for (const project of this.projects.values()) {
      const group = project.users[account_id];
      if (VISIBLE_GROUPS.has(group)) {
        rows.set(project.project_id, { title: project.title, group });
      }
    }
    return rows;
  }
}

const MAX_PROJECTS = 6;

/**
 * Generate the next operation for the current model state. Deterministic for
 * a given rng state and model. Faults are generated by the runner, not here.
 */
export function generateOp(model, rng, step) {
  const accounts = [...model.accounts.keys()];
  const projects = [...model.projects.keys()];
  const kinds = [];
  const add = (kind, weight) => {
    for (let i = 0; i < weight; i++) kinds.push(kind);
  };
  if (projects.length < MAX_PROJECTS)
    add("create", projects.length < 2 ? 6 : 2);
  if (projects.length > 0) {
    add("rename", 4);
    add("invite", 3);
    add("set-role", 2);
    add("remove", 2);
    add("transfer", 1);
  }
  const kind = rng.pick(kinds);
  const title = `t${step}-${rng.int(0, 9999)}`;
  if (kind === "create") {
    return { kind, actor: rng.pick(accounts), title, expect: "ok" };
  }
  const project_id = rng.pick(projects);
  const members = model.members(project_id);
  const nonMembers = accounts.filter((a) => !members.includes(a));
  const owner = members.find((a) => model.group(project_id, a) === "owner");
  const nonOwners = members.filter((a) => a !== owner);
  // Most operations by someone who should succeed; some deliberately by a
  // non-member, which must be refused.
  const byOutsider = nonMembers.length > 0 && rng.chance(0.25);
  const outsider = byOutsider ? rng.pick(nonMembers) : null;
  const renameBy = (actor) => ({
    kind: "rename",
    actor,
    project_id,
    title,
    expect: "ok",
  });

  switch (kind) {
    case "rename": {
      const actor = outsider ?? rng.pick(members);
      const group = model.group(project_id, actor);
      const expect =
        group === "owner" || group === "collaborator" ? "ok" : "fail";
      return { kind, actor, project_id, title, expect };
    }
    case "invite": {
      const targets = nonMembers.filter((a) => a !== outsider);
      if (targets.length === 0) return renameBy(owner);
      const target = rng.pick(targets);
      if (outsider) {
        return { kind, actor: outsider, project_id, target, expect: "fail" };
      }
      const actor = rng.chance(0.6) ? owner : rng.pick(members);
      const expect = actor === owner ? "ok" : "either";
      return { kind, actor, project_id, target, expect };
    }
    case "set-role": {
      if (nonOwners.length === 0) return renameBy(owner);
      const target = rng.pick(nonOwners);
      const role = rng.pick(["collaborator", "viewer"]);
      const actor = outsider ?? owner;
      const expect = outsider ? "fail" : "ok";
      return { kind, actor, project_id, target, role, expect };
    }
    case "remove": {
      if (nonOwners.length === 0) return renameBy(owner);
      const target = rng.pick(nonOwners);
      const actor = outsider ?? owner;
      const expect = outsider ? "fail" : "ok";
      return { kind, actor, project_id, target, expect };
    }
    case "transfer": {
      if (nonOwners.length === 0) return renameBy(owner);
      const target = rng.pick(nonOwners);
      if (outsider) {
        return { kind, actor: outsider, project_id, target, expect: "fail" };
      }
      const expect =
        model.group(project_id, target) === "collaborator" ? "ok" : "fail";
      return { kind, actor: owner, project_id, target, expect };
    }
  }
  throw new Error(`unknown operation kind ${kind}`);
}

/** During a fault an allowed operation may fail; a forbidden one never succeeds. */
export function expectDuringFault(expect) {
  return expect === "ok" ? "either" : expect;
}
