/* CoCalc: Copyright © 2026 SageMath, Inc. License: MS-RSL. */

// A shared manual reading corpus; include unsupported constructs to expose gaps.
export const MARKDOWN_SAMPLE = [
  "# Markdown reading laboratory",
  "",
  "This message stays on your phone. Use it to check **reading**, scrolling, text selection, code wrapping, and read-aloud. Some examples deliberately exercise features the native renderer does not support yet; literal TeX, HTML, or image placeholders identify those gaps.",
  "",
  "## Text and typography",
  "",
  "A paragraph with **bold**, *italic*, ***bold italic***, ~~strikethrough~~, and `inline_code`. Unicode: café, naïve, Ελληνικά, 日本語, ∀ ε > 0. Emoji: :smile: :rocket: and 🎉. A hashtag: #mathematics.",
  "",
  "This sentence wraps in the Markdown source",
  "but should read as one sentence.",
  "",
  "This line has a deliberate hard break.  ",
  "This is the next line.",
  "",
  "### A third-level heading",
  "#### A fourth-level heading",
  "",
  "## Lists and tasks",
  "",
  "3. An ordered list starting at three.",
  "   - A nested bullet with **emphasis**.",
  "   - Another bullet with `code`.",
  "4. The outer numbering should continue at four.",
  "",
  "- [x] Completed task",
  "- [ ] Pending task",
  "- [x] Readable at a larger system text size",
  "",
  "> A quoted explanation with **important text**.",
  ">",
  "> > A nested quote: mathematics should remain readable on a small screen.",
  "",
  "---",
  "",
  "## Code",
  "",
  "```python",
  "from fractions import Fraction",
  "",
  "def harmonic(n):",
  "    return sum((Fraction(1, k) for k in range(1, n + 1)), Fraction(0))",
  "",
  'print(harmonic(20), "This deliberately long line lets you compare horizontal scrolling with Wrap code on your phone.")',
  "```",
  "",
  "```json",
  '{"agent": "Markdown", "checks": ["copy", "wrap", "selection"], "ready": true}',
  "```",
  "",
  "## Tables",
  "",
  "| Feature | Result | Count |",
  "|:---|:---:|---:|",
  "| **Parsing** | Ready | 42 |",
  "| `Code` | Wrap / copy | 12 |",
  "| Math | TeX fallback for now | 8 |",
  "",
  "Read aloud should associate each value with its column heading.",
  "",
  "## Links and mentions",
  "",
  "[CoCalc documentation](https://doc.cocalc.com/) and a [reference-style link][guide].",
  "",
  'A person mention: <span class="user-mention" account-id=47d0393e-4814-4452-bb6c-35bac4cbd314>@William</span>.',
  "",
  "## Inline mathematics",
  "",
  "Dollar delimiters: $e^{i\\pi}+1=0$. Parenthesis delimiters: \\(a^2+b^2=c^2\\). Subscripts should remain intact: $x_1+x_2+\\cdots+x_n$.",
  "",
  "## Display mathematics",
  "",
  "$$",
  "\\int_0^1 x^2\\,dx = \\frac{1}{3}",
  "$$",
  "",
  "\\[",
  "\\begin{pmatrix}1 & 2 \\\\ 3 & 4\\end{pmatrix}",
  "\\begin{pmatrix}x \\\\ y\\end{pmatrix}",
  "= \\begin{pmatrix}x+2y \\\\ 3x+4y\\end{pmatrix}",
  "\\]",
  "",
  "\\begin{equation}",
  "\\sum_{n=1}^{\\infty}\\frac{1}{n^2}=\\frac{\\pi^2}{6}",
  "\\end{equation}",
  "",
  "$$",
  "\\begin{aligned}",
  "f(x) &= x^2+2x+1 \\\\",
  "     &= (x+1)^2",
  "\\end{aligned}",
  "$$",
  "",
  "## CoCalc macro compatibility",
  "",
  "These exercise CoCalc's macro configuration: $\\ZZ$, $\\QQ$, $\\GF{7}$, and $\\Bold{x}$.",
  "",
  "A local macro definition and use:",
  "",
  "$$",
  "\\newcommand{\\vect}[1]{\\mathbf{#1}}",
  "\\vect{v} = \\begin{pmatrix}1\\\\2\\\\3\\end{pmatrix}",
  "$$",
  "",
  "## HTML and images — parity checks",
  "",
  "<details>",
  "<summary>Details summary</summary>",
  "",
  "A paragraph inside details, including **bold text** and $x^2$.",
  "",
  "</details>",
  "",
  "Text with <sup>superscript</sup>, <sub>subscript</sub>, and <u>underline</u>.",
  "",
  "![A sample plot placeholder](preview-plot.png)",
  "",
  "## End of sample",
  "",
  "Try **Read aloud**, select some text, or send a local message. Return to this conversation to check that it keeps its own history.",
  "",
  '[guide]: https://doc.cocalc.com/ "CoCalc guide"',
].join("\n");
