import { downloadHTML } from "./download-html";

describe("generated HTML delivery", () => {
  beforeEach(() => {
    jest.useFakeTimers();
    URL.createObjectURL = jest.fn(() => "blob:generated-html");
    URL.revokeObjectURL = jest.fn();
  });
  afterEach(() => {
    jest.runOnlyPendingTimers();
    jest.useRealTimers();
    jest.restoreAllMocks();
  });

  it("downloads the generated bytes with an HTML filename and releases the URL", async () => {
    const html = '<!doctype html><img src="data:image/png;base64,abcd">';
    const click = jest
      .spyOn(HTMLAnchorElement.prototype, "click")
      .mockImplementation(function (this: HTMLAnchorElement) {
        expect(this.href).toBe("blob:generated-html");
        expect(this.download).toBe("My notebook.html");
        expect(document.body.contains(this)).toBe(true);
      });
    downloadHTML(html, "My notebook.html");
    expect(click).toHaveBeenCalledTimes(1);
    const blob = (URL.createObjectURL as jest.Mock).mock.calls[0][0];
    expect(blob.type).toBe("text/html;charset=utf-8");
    const contents = await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.readAsText(blob);
    });
    expect(contents).toBe(html);
    expect(document.querySelector("a[download]")).toBeNull();
    expect(URL.revokeObjectURL).not.toHaveBeenCalled();
    jest.advanceTimersByTime(60_000);
    expect(URL.revokeObjectURL).toHaveBeenCalledWith("blob:generated-html");
  });

  it("propagates delivery errors and cleans up the anchor and URL", () => {
    jest.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {
      throw Error("download failed");
    });
    expect(() => downloadHTML("html", "test.html")).toThrow("download failed");
    expect(document.querySelector("a[download]")).toBeNull();
    jest.advanceTimersByTime(60_000);
    expect(URL.revokeObjectURL).toHaveBeenCalledTimes(1);
  });
});
