/* eslint-disable */
// This file is auto-generated by scripts/generate-api-v2-manifest.js.
// Do not edit manually.

import type { Request, Response } from "express";
import handler0 from "../pages/api/v2/accounts/ban";
import handler1 from "../pages/api/v2/accounts/delete";
import handler2 from "../pages/api/v2/accounts/get-email-address";
import handler3 from "../pages/api/v2/accounts/get-names";
import handler4 from "../pages/api/v2/accounts/profile";
import handler5 from "../pages/api/v2/accounts/remove-ban";
import handler6 from "../pages/api/v2/accounts/search";
import handler7 from "../pages/api/v2/accounts/send-verification-email";
import handler8 from "../pages/api/v2/accounts/set-email-address";
import handler9 from "../pages/api/v2/accounts/set-name";
import handler10 from "../pages/api/v2/accounts/set-password";
import handler11 from "../pages/api/v2/accounts/sign-out";
import handler12 from "../pages/api/v2/api-keys";
import handler13 from "../pages/api/v2/auth/2fa/disable";
import handler14 from "../pages/api/v2/auth/2fa/recovery-codes/rotate";
import handler15 from "../pages/api/v2/auth/2fa/setup/confirm";
import handler16 from "../pages/api/v2/auth/2fa/setup/start";
import handler17 from "../pages/api/v2/auth/2fa/status";
import handler18 from "../pages/api/v2/auth/bootstrap";
import handler19 from "../pages/api/v2/auth/fresh-auth-status";
import handler20 from "../pages/api/v2/auth/fresh-auth";
import handler21 from "../pages/api/v2/auth/has-password";
import handler22 from "../pages/api/v2/auth/password-reset";
import handler23 from "../pages/api/v2/auth/password-strength";
import handler24 from "../pages/api/v2/auth/redeem-password-reset";
import handler25 from "../pages/api/v2/auth/redeem-verify-email";
import handler26 from "../pages/api/v2/auth/requires-token";
import handler27 from "../pages/api/v2/auth/sign-in";
import handler28 from "../pages/api/v2/auth/sign-up";
import handler29 from "../pages/api/v2/auth/sso-strategies";
import handler30 from "../pages/api/v2/auth/unlink-strategy";
import handler31 from "../pages/api/v2/auth/verify-second-factor";
import handler32 from "../pages/api/v2/billing/cancel-subscription";
import handler33 from "../pages/api/v2/billing/create-payment-method";
import handler34 from "../pages/api/v2/billing/delete-payment-method";
import handler35 from "../pages/api/v2/billing/get-customer";
import handler36 from "../pages/api/v2/billing/get-invoice-url";
import handler37 from "../pages/api/v2/billing/get-invoice";
import handler38 from "../pages/api/v2/billing/get-invoices-and-receipts";
import handler39 from "../pages/api/v2/billing/get-subscriptions";
import handler40 from "../pages/api/v2/bookmarks/add";
import handler41 from "../pages/api/v2/bookmarks/get";
import handler42 from "../pages/api/v2/bookmarks/remove";
import handler43 from "../pages/api/v2/bookmarks/set";
import handler44 from "../pages/api/v2/customize";
import handler45 from "../pages/api/v2/exec";
import handler46 from "../pages/api/v2/file-access";
import handler47 from "../pages/api/v2/guesslang";
import handler48 from "../pages/api/v2/index";
import handler49 from "../pages/api/v2/messages/get";
import handler50 from "../pages/api/v2/messages/send";
import handler51 from "../pages/api/v2/news/admin-get";
import handler52 from "../pages/api/v2/news/admin-list";
import handler53 from "../pages/api/v2/news/edit";
import handler54 from "../pages/api/v2/news/events";
import handler55 from "../pages/api/v2/news/get";
import handler56 from "../pages/api/v2/news/list";
import handler57 from "../pages/api/v2/projects/collaborators/add";
import handler58 from "../pages/api/v2/projects/collaborators/list";
import handler59 from "../pages/api/v2/projects/collaborators/remove";
import handler60 from "../pages/api/v2/projects/copy-path";
import handler61 from "../pages/api/v2/projects/copy-url";
import handler62 from "../pages/api/v2/projects/course/set-course-info";
import handler63 from "../pages/api/v2/projects/create";
import handler64 from "../pages/api/v2/projects/delete";
import handler65 from "../pages/api/v2/projects/filename-search";
import handler66 from "../pages/api/v2/projects/get-one";
import handler67 from "../pages/api/v2/projects/get";
import handler68 from "../pages/api/v2/projects/restore";
import handler69 from "../pages/api/v2/projects/set-admin-quotas";
import handler70 from "../pages/api/v2/projects/start";
import handler71 from "../pages/api/v2/projects/stop";
import handler72 from "../pages/api/v2/projects/touch";
import handler73 from "../pages/api/v2/projects/update";
import handler74 from "../pages/api/v2/purchases/admin-purchase";
import handler75 from "../pages/api/v2/purchases/cancel-automatic-billing";
import handler76 from "../pages/api/v2/purchases/cancel-current-checkout-session";
import handler77 from "../pages/api/v2/purchases/cancel-subscription";
import handler78 from "../pages/api/v2/purchases/cost-to-resume-subscription";
import handler79 from "../pages/api/v2/purchases/create-refund";
import handler80 from "../pages/api/v2/purchases/email-statement";
import handler81 from "../pages/api/v2/purchases/get-balance-admin";
import handler82 from "../pages/api/v2/purchases/get-balance";
import handler83 from "../pages/api/v2/purchases/get-charges-by-service";
import handler84 from "../pages/api/v2/purchases/get-closing-dates";
import handler85 from "../pages/api/v2/purchases/get-cost-per-day";
import handler86 from "../pages/api/v2/purchases/get-current-checkout-session";
import handler87 from "../pages/api/v2/purchases/get-live-subscriptions";
import handler88 from "../pages/api/v2/purchases/get-llm-usage";
import handler89 from "../pages/api/v2/purchases/get-membership-tiers";
import handler90 from "../pages/api/v2/purchases/get-membership";
import handler91 from "../pages/api/v2/purchases/get-min-balance";
import handler92 from "../pages/api/v2/purchases/get-purchases-admin";
import handler93 from "../pages/api/v2/purchases/get-purchases";
import handler94 from "../pages/api/v2/purchases/get-quotas";
import handler95 from "../pages/api/v2/purchases/get-service-cost";
import handler96 from "../pages/api/v2/purchases/get-shopping-cart-checkout-params";
import handler97 from "../pages/api/v2/purchases/get-spend-rate";
import handler98 from "../pages/api/v2/purchases/get-statements";
import handler99 from "../pages/api/v2/purchases/get-stripe-publishable-key";
import handler100 from "../pages/api/v2/purchases/get-subscriptions";
import handler101 from "../pages/api/v2/purchases/get-unpaid-invoices";
import handler102 from "../pages/api/v2/purchases/is-purchase-allowed";
import handler103 from "../pages/api/v2/purchases/membership-change";
import handler104 from "../pages/api/v2/purchases/membership-quote";
import handler105 from "../pages/api/v2/purchases/renew-subscription";
import handler106 from "../pages/api/v2/purchases/reset-closing-date";
import handler107 from "../pages/api/v2/purchases/resume-subscription";
import handler108 from "../pages/api/v2/purchases/set-quota";
import handler109 from "../pages/api/v2/purchases/setup-automatic-billing";
import handler110 from "../pages/api/v2/purchases/shopping-cart-checkout";
import handler111 from "../pages/api/v2/purchases/stripe/cancel-payment-intent";
import handler112 from "../pages/api/v2/purchases/stripe/create-payment-intent";
import handler113 from "../pages/api/v2/purchases/stripe/create-setup-intent";
import handler114 from "../pages/api/v2/purchases/stripe/create-subscription-payment";
import handler115 from "../pages/api/v2/purchases/stripe/delete-payment-method";
import handler116 from "../pages/api/v2/purchases/stripe/get-checkout-session";
import handler117 from "../pages/api/v2/purchases/stripe/get-customer-session";
import handler118 from "../pages/api/v2/purchases/stripe/get-customer";
import handler119 from "../pages/api/v2/purchases/stripe/get-open-payments";
import handler120 from "../pages/api/v2/purchases/stripe/get-payment-method";
import handler121 from "../pages/api/v2/purchases/stripe/get-payment-methods";
import handler122 from "../pages/api/v2/purchases/stripe/get-payments";
import handler123 from "../pages/api/v2/purchases/stripe/process-payment-intents";
import handler124 from "../pages/api/v2/purchases/stripe/set-customer";
import handler125 from "../pages/api/v2/purchases/stripe/set-default-payment-method";
import handler126 from "../pages/api/v2/purchases/student-pay-transfer";
import handler127 from "../pages/api/v2/purchases/student-pay";
import handler128 from "../pages/api/v2/purchases/sync-subscription";
import handler129 from "../pages/api/v2/salesloft/money";
import handler130 from "../pages/api/v2/shopping/cart/add";
import handler131 from "../pages/api/v2/shopping/cart/checked";
import handler132 from "../pages/api/v2/shopping/cart/delete";
import handler133 from "../pages/api/v2/shopping/cart/edit";
import handler134 from "../pages/api/v2/shopping/cart/get";
import handler135 from "../pages/api/v2/shopping/cart/processing";
import handler136 from "../pages/api/v2/shopping/cart/recent-purchases";
import handler137 from "../pages/api/v2/shopping/cart/remove";
import handler138 from "../pages/api/v2/software/activate";
import handler139 from "../pages/api/v2/software/status";
import handler140 from "../pages/api/v2/support/create-ticket";
import handler141 from "../pages/api/v2/support/tickets";
import handler142 from "../pages/api/v2/user-query";
import handler143 from "../pages/api/v2/vouchers/charge-for-unpaid-vouchers";
import handler144 from "../pages/api/v2/vouchers/create";
import handler145 from "../pages/api/v2/vouchers/get-voucher-codes";
import handler146 from "../pages/api/v2/vouchers/recent-vouchers";
import handler147 from "../pages/api/v2/vouchers/redeem";
import handler148 from "../pages/api/v2/vouchers/set-voucher-code-notes";

export type ApiV2Handler = (req: Request, res: Response) => any;

export type ApiV2ManifestEntry = { path: string; handler: ApiV2Handler };

export const apiV2Manifest: ApiV2ManifestEntry[] = [
  { path: "/accounts/ban", handler: handler0 },
  { path: "/accounts/delete", handler: handler1 },
  { path: "/accounts/get-email-address", handler: handler2 },
  { path: "/accounts/get-names", handler: handler3 },
  { path: "/accounts/profile", handler: handler4 },
  { path: "/accounts/remove-ban", handler: handler5 },
  { path: "/accounts/search", handler: handler6 },
  { path: "/accounts/send-verification-email", handler: handler7 },
  { path: "/accounts/set-email-address", handler: handler8 },
  { path: "/accounts/set-name", handler: handler9 },
  { path: "/accounts/set-password", handler: handler10 },
  { path: "/accounts/sign-out", handler: handler11 },
  { path: "/api-keys", handler: handler12 },
  { path: "/auth/2fa/disable", handler: handler13 },
  { path: "/auth/2fa/recovery-codes/rotate", handler: handler14 },
  { path: "/auth/2fa/setup/confirm", handler: handler15 },
  { path: "/auth/2fa/setup/start", handler: handler16 },
  { path: "/auth/2fa/status", handler: handler17 },
  { path: "/auth/bootstrap", handler: handler18 },
  { path: "/auth/fresh-auth-status", handler: handler19 },
  { path: "/auth/fresh-auth", handler: handler20 },
  { path: "/auth/has-password", handler: handler21 },
  { path: "/auth/password-reset", handler: handler22 },
  { path: "/auth/password-strength", handler: handler23 },
  { path: "/auth/redeem-password-reset", handler: handler24 },
  { path: "/auth/redeem-verify-email", handler: handler25 },
  { path: "/auth/requires-token", handler: handler26 },
  { path: "/auth/sign-in", handler: handler27 },
  { path: "/auth/sign-up", handler: handler28 },
  { path: "/auth/sso-strategies", handler: handler29 },
  { path: "/auth/unlink-strategy", handler: handler30 },
  { path: "/auth/verify-second-factor", handler: handler31 },
  { path: "/billing/cancel-subscription", handler: handler32 },
  { path: "/billing/create-payment-method", handler: handler33 },
  { path: "/billing/delete-payment-method", handler: handler34 },
  { path: "/billing/get-customer", handler: handler35 },
  { path: "/billing/get-invoice-url", handler: handler36 },
  { path: "/billing/get-invoice", handler: handler37 },
  { path: "/billing/get-invoices-and-receipts", handler: handler38 },
  { path: "/billing/get-subscriptions", handler: handler39 },
  { path: "/bookmarks/add", handler: handler40 },
  { path: "/bookmarks/get", handler: handler41 },
  { path: "/bookmarks/remove", handler: handler42 },
  { path: "/bookmarks/set", handler: handler43 },
  { path: "/customize", handler: handler44 },
  { path: "/exec", handler: handler45 },
  { path: "/file-access", handler: handler46 },
  { path: "/guesslang", handler: handler47 },
  { path: "/", handler: handler48 },
  { path: "/messages/get", handler: handler49 },
  { path: "/messages/send", handler: handler50 },
  { path: "/news/admin-get", handler: handler51 },
  { path: "/news/admin-list", handler: handler52 },
  { path: "/news/edit", handler: handler53 },
  { path: "/news/events", handler: handler54 },
  { path: "/news/get", handler: handler55 },
  { path: "/news/list", handler: handler56 },
  { path: "/projects/collaborators/add", handler: handler57 },
  { path: "/projects/collaborators/list", handler: handler58 },
  { path: "/projects/collaborators/remove", handler: handler59 },
  { path: "/projects/copy-path", handler: handler60 },
  { path: "/projects/copy-url", handler: handler61 },
  { path: "/projects/course/set-course-info", handler: handler62 },
  { path: "/projects/create", handler: handler63 },
  { path: "/projects/delete", handler: handler64 },
  { path: "/projects/filename-search", handler: handler65 },
  { path: "/projects/get-one", handler: handler66 },
  { path: "/projects/get", handler: handler67 },
  { path: "/projects/restore", handler: handler68 },
  { path: "/projects/set-admin-quotas", handler: handler69 },
  { path: "/projects/start", handler: handler70 },
  { path: "/projects/stop", handler: handler71 },
  { path: "/projects/touch", handler: handler72 },
  { path: "/projects/update", handler: handler73 },
  { path: "/purchases/admin-purchase", handler: handler74 },
  { path: "/purchases/cancel-automatic-billing", handler: handler75 },
  { path: "/purchases/cancel-current-checkout-session", handler: handler76 },
  { path: "/purchases/cancel-subscription", handler: handler77 },
  { path: "/purchases/cost-to-resume-subscription", handler: handler78 },
  { path: "/purchases/create-refund", handler: handler79 },
  { path: "/purchases/email-statement", handler: handler80 },
  { path: "/purchases/get-balance-admin", handler: handler81 },
  { path: "/purchases/get-balance", handler: handler82 },
  { path: "/purchases/get-charges-by-service", handler: handler83 },
  { path: "/purchases/get-closing-dates", handler: handler84 },
  { path: "/purchases/get-cost-per-day", handler: handler85 },
  { path: "/purchases/get-current-checkout-session", handler: handler86 },
  { path: "/purchases/get-live-subscriptions", handler: handler87 },
  { path: "/purchases/get-llm-usage", handler: handler88 },
  { path: "/purchases/get-membership-tiers", handler: handler89 },
  { path: "/purchases/get-membership", handler: handler90 },
  { path: "/purchases/get-min-balance", handler: handler91 },
  { path: "/purchases/get-purchases-admin", handler: handler92 },
  { path: "/purchases/get-purchases", handler: handler93 },
  { path: "/purchases/get-quotas", handler: handler94 },
  { path: "/purchases/get-service-cost", handler: handler95 },
  { path: "/purchases/get-shopping-cart-checkout-params", handler: handler96 },
  { path: "/purchases/get-spend-rate", handler: handler97 },
  { path: "/purchases/get-statements", handler: handler98 },
  { path: "/purchases/get-stripe-publishable-key", handler: handler99 },
  { path: "/purchases/get-subscriptions", handler: handler100 },
  { path: "/purchases/get-unpaid-invoices", handler: handler101 },
  { path: "/purchases/is-purchase-allowed", handler: handler102 },
  { path: "/purchases/membership-change", handler: handler103 },
  { path: "/purchases/membership-quote", handler: handler104 },
  { path: "/purchases/renew-subscription", handler: handler105 },
  { path: "/purchases/reset-closing-date", handler: handler106 },
  { path: "/purchases/resume-subscription", handler: handler107 },
  { path: "/purchases/set-quota", handler: handler108 },
  { path: "/purchases/setup-automatic-billing", handler: handler109 },
  { path: "/purchases/shopping-cart-checkout", handler: handler110 },
  { path: "/purchases/stripe/cancel-payment-intent", handler: handler111 },
  { path: "/purchases/stripe/create-payment-intent", handler: handler112 },
  { path: "/purchases/stripe/create-setup-intent", handler: handler113 },
  { path: "/purchases/stripe/create-subscription-payment", handler: handler114 },
  { path: "/purchases/stripe/delete-payment-method", handler: handler115 },
  { path: "/purchases/stripe/get-checkout-session", handler: handler116 },
  { path: "/purchases/stripe/get-customer-session", handler: handler117 },
  { path: "/purchases/stripe/get-customer", handler: handler118 },
  { path: "/purchases/stripe/get-open-payments", handler: handler119 },
  { path: "/purchases/stripe/get-payment-method", handler: handler120 },
  { path: "/purchases/stripe/get-payment-methods", handler: handler121 },
  { path: "/purchases/stripe/get-payments", handler: handler122 },
  { path: "/purchases/stripe/process-payment-intents", handler: handler123 },
  { path: "/purchases/stripe/set-customer", handler: handler124 },
  { path: "/purchases/stripe/set-default-payment-method", handler: handler125 },
  { path: "/purchases/student-pay-transfer", handler: handler126 },
  { path: "/purchases/student-pay", handler: handler127 },
  { path: "/purchases/sync-subscription", handler: handler128 },
  { path: "/salesloft/money", handler: handler129 },
  { path: "/shopping/cart/add", handler: handler130 },
  { path: "/shopping/cart/checked", handler: handler131 },
  { path: "/shopping/cart/delete", handler: handler132 },
  { path: "/shopping/cart/edit", handler: handler133 },
  { path: "/shopping/cart/get", handler: handler134 },
  { path: "/shopping/cart/processing", handler: handler135 },
  { path: "/shopping/cart/recent-purchases", handler: handler136 },
  { path: "/shopping/cart/remove", handler: handler137 },
  { path: "/software/activate", handler: handler138 },
  { path: "/software/status", handler: handler139 },
  { path: "/support/create-ticket", handler: handler140 },
  { path: "/support/tickets", handler: handler141 },
  { path: "/user-query", handler: handler142 },
  { path: "/vouchers/charge-for-unpaid-vouchers", handler: handler143 },
  { path: "/vouchers/create", handler: handler144 },
  { path: "/vouchers/get-voucher-codes", handler: handler145 },
  { path: "/vouchers/recent-vouchers", handler: handler146 },
  { path: "/vouchers/redeem", handler: handler147 },
  { path: "/vouchers/set-voucher-code-notes", handler: handler148 },
];
