/*
 *  This file is part of CoCalc: Copyright © 2026 Sagemath, Inc.
 *  License: MS-RSL – see LICENSE.md for details
 */

export const ADMIN_DATA_EXPLORER_SQL_DEFAULT_LIMIT = 100;
export const ADMIN_DATA_EXPLORER_SQL_MAX_LIMIT = 5_000;
export const ADMIN_DATA_EXPLORER_SQL_DEFAULT_TIMEOUT_MS = 5_000;
export const ADMIN_DATA_EXPLORER_SQL_MAX_TIMEOUT_MS = 30_000;
export const ADMIN_DATA_EXPLORER_SQL_DEFAULT_MAX_BYTES = 4 * 1024 * 1024;
export const ADMIN_DATA_EXPLORER_SQL_MAX_BYTES = 32 * 1024 * 1024;

export const ADMIN_DATA_EXPLORER_ALLOWED_SQL_RELATIONS = [
  "account_cpu_usage_events",
  "account_managed_egress_events",
  "account_security_state",
  "account_usage_windows",
  "accounts",
  "admin_data_explorer_views",
  "ai_usage_log",
  "central_log",
  "launch_smoke_results",
  "project_hosts",
  "project_runtime_slots",
  "projects",
  "purchases",
  "statements",
  "usage_info",
  "ux_latency_events",
  "voucher_codes",
  "vouchers",
] as const;

export const ADMIN_DATA_EXPLORER_ALLOWED_SQL_FUNCTIONS = [
  "abs",
  "avg",
  "ceil",
  "coalesce",
  "count",
  "date_trunc",
  "floor",
  "greatest",
  "jsonb_array_length",
  "jsonb_extract_path_text",
  "least",
  "left",
  "length",
  "lower",
  "max",
  "min",
  "now",
  "right",
  "round",
  "split_part",
  "substring",
  "sum",
  "to_char",
  "upper",
] as const;

export const ADMIN_DATA_EXPLORER_ALLOWED_SQL_COLUMNS = {
  account_cpu_usage_events: [
    "account_id",
    "project_id",
    "host_id",
    "bay_id",
    "time",
    "created",
    "created_at",
    "updated",
    "updated_at",
    "event_type",
    "metric",
    "duration_ms",
    "value",
  ],
  account_managed_egress_events: [
    "account_id",
    "project_id",
    "host_id",
    "bay_id",
    "time",
    "created",
    "created_at",
    "updated",
    "updated_at",
    "category",
    "bytes",
    "value",
  ],
  account_security_state: [
    "account_id",
    "created",
    "updated",
    "last_seen",
    "state",
    "reason",
    "metadata",
  ],
  account_usage_windows: [
    "account_id",
    "window",
    "created",
    "updated",
    "started_at",
    "ended_at",
    "usage",
    "metadata",
  ],
  accounts: [
    "account_id",
    "email_address",
    "first_name",
    "last_name",
    "created",
    "last_active",
    "banned",
    "deleted",
  ],
  admin_data_explorer_views: [
    "id",
    "slug",
    "title",
    "description",
    "tags",
    "visibility",
    "query_kind",
    "query",
    "scope",
    "default_columns",
    "default_sort",
    "default_limit",
    "visualization",
    "owner_account_id",
    "created_at",
    "updated_at",
    "version",
  ],
  ai_usage_log: [
    "id",
    "time",
    "account_id",
    "project_id",
    "path",
    "model",
    "tag",
    "total_tokens",
    "prompt_tokens",
    "total_time_s",
    "usage_units",
    "expire",
  ],
  central_log: ["id", "event", "value", "time", "expire"],
  launch_smoke_results: [
    "id",
    "created_at",
    "bay_id",
    "host_id",
    "project_id",
    "status",
    "duration_ms",
    "result",
    "metadata",
  ],
  project_hosts: [
    "id",
    "name",
    "region",
    "bay_id",
    "public_url",
    "internal_url",
    "ssh_server",
    "status",
    "last_seen",
    "version",
    "capacity",
    "updated",
    "created",
    "deleted",
    "metadata",
    "tier",
    "deletion_protection",
  ],
  project_runtime_slots: [
    "sponsor_account_id",
    "project_id",
    "owning_bay_id",
    "host_id",
    "state",
    "actor_account_id",
    "reason",
    "acquired_at",
    "heartbeat_at",
    "expires_at",
    "op_id",
    "metadata",
  ],
  projects: [
    "project_id",
    "title",
    "state",
    "host_id",
    "owning_bay_id",
    "created",
    "last_edited",
    "deleted",
  ],
  purchases: [
    "id",
    "time",
    "account_id",
    "cost",
    "pending",
    "cost_per_hour",
    "cost_so_far",
    "period_start",
    "period_end",
    "invoice_id",
    "project_id",
    "service",
    "description",
    "tag",
    "day_statement_id",
  ],
  statements: [
    "id",
    "interval",
    "account_id",
    "time",
    "balance",
    "total_charges",
    "num_charges",
    "total_credits",
    "num_credits",
    "paid_purchase_id",
    "automatic_payment",
    "automatic_payment_intent_id",
    "last_sent",
  ],
  usage_info: ["project_id", "path", "usage"],
  ux_latency_events: [
    "event_type",
    "metric",
    "duration_ms",
    "project_id",
    "host_id",
    "bay_id",
    "started_at",
    "created_at",
    "metadata",
  ],
  voucher_codes: [
    "code",
    "id",
    "created",
    "when_redeemed",
    "redeemed_by",
    "canceled",
    "purchase_ids",
    "notes",
  ],
  vouchers: [
    "id",
    "when_pay",
    "created_by",
    "created",
    "title",
    "active",
    "expire",
    "cancel_by",
    "count",
    "cost",
    "tax",
    "notes",
    "purchased",
  ],
} as const satisfies Record<
  (typeof ADMIN_DATA_EXPLORER_ALLOWED_SQL_RELATIONS)[number],
  readonly string[]
>;

export type AdminDataExplorerAllowedSqlRelation =
  (typeof ADMIN_DATA_EXPLORER_ALLOWED_SQL_RELATIONS)[number];

export type AdminDataExplorerAllowedSqlFunction =
  (typeof ADMIN_DATA_EXPLORER_ALLOWED_SQL_FUNCTIONS)[number];

export const ADMIN_DATA_EXPLORER_SQL_CONSTRAINTS = {
  default_limit: ADMIN_DATA_EXPLORER_SQL_DEFAULT_LIMIT,
  max_limit: ADMIN_DATA_EXPLORER_SQL_MAX_LIMIT,
  default_timeout_ms: ADMIN_DATA_EXPLORER_SQL_DEFAULT_TIMEOUT_MS,
  max_timeout_ms: ADMIN_DATA_EXPLORER_SQL_MAX_TIMEOUT_MS,
  default_max_bytes: ADMIN_DATA_EXPLORER_SQL_DEFAULT_MAX_BYTES,
  max_bytes: ADMIN_DATA_EXPLORER_SQL_MAX_BYTES,
  allowed_relations: ADMIN_DATA_EXPLORER_ALLOWED_SQL_RELATIONS,
  allowed_functions: ADMIN_DATA_EXPLORER_ALLOWED_SQL_FUNCTIONS,
  allowed_columns: ADMIN_DATA_EXPLORER_ALLOWED_SQL_COLUMNS,
} as const;
