/*
 *  This file is part of CoCalc: Copyright © 2026 Sagemath, Inc.
 *  License: MS-RSL – see LICENSE.md for details
 */

// Built-in starting templates for the admin membership-tier editor. These
// mirror /home/user/scratch/cocalc-membership-tiers-2026-06-20-183541.json.
export const TIER_TEMPLATES = {
  admin: {
    id: "admin",
    label: "Admin",
    store_visible: false,
    store_description: null,
    store_highlights: [],
    site_license_pool_description: null,
    team_visible: false,
    course_store_visible: false,
    course_allowed_domains: [],
    priority: 31,
    price_monthly: 0,
    price_yearly: 0,
    trial_days: null,
    course_price: null,
    course_duration_days: null,
    course_grace_days: null,
    project_defaults: {
      memory: 16000,
      disk_quota: 50000,
      memory_request: 0,
    },
    ai_limits: {
      units_5h: 0,
      units_7d: 0,
    },
    features: {
      create_hosts: true,
      project_host_tier: 10,
    },
    usage_limits: {
      max_projects: 1000,
      rootfs_count: 250,
      cpu_5h_seconds: 3600000,
      cpu_7d_seconds: 36000000,
      egress_5h_bytes: 30000000000,
      egress_7d_bytes: 200000000000,
      rootfs_oci_images: true,
      blob_account_count: 50000,
      blob_project_count: 5000,
      rootfs_max_storage_gb: 30,
      invite_email_allow_urls: false,
      max_backups_per_project: 15,
      rootfs_total_storage_gb: 250,
      shared_compute_priority: 4,
      blob_account_total_bytes: 25000000000,
      blob_project_total_bytes: 5000000000,
      invite_email_daily_count: 1000,
      total_storage_hard_bytes: 650000000000,
      total_storage_soft_bytes: 600000000000,
      acp_max_queued_per_thread: 100,
      credit_spend_limit_5h_usd: 300,
      credit_spend_limit_7d_usd: 1000,
      invite_email_hourly_count: 500,
      invite_email_send_enabled: true,
      max_snapshots_per_project: 20,
      acp_max_queued_per_account: 500,
      acp_max_running_per_account: 50,
      acp_max_running_per_project: 50,
      acp_max_created_5h_per_account: 500,
      acp_max_created_7d_per_account: 2000,
      invite_email_link_copy_enabled: true,
      max_sponsored_running_projects: 50,
      invite_email_allow_course_title: true,
      invite_email_pending_per_course: 1000,
      prepaid_host_usage_limit_5h_usd: 1000,
      prepaid_host_usage_limit_7d_usd: 3000,
      invite_email_allow_project_title: true,
      invite_email_pending_per_project: 500,
      notification_email_send_limit_5h: 1000,
      notification_email_send_limit_7d: 5000,
      invite_email_recipients_per_batch: 500,
      invite_email_resend_cooldown_minutes: 15,
      invite_email_custom_message_max_chars: 1000,
      acp_max_active_automations_per_project: 20,
      course_max_students_and_pending_invites: 1000,
      project_max_collaborators_and_pending_invites: 500,
    },
    pricing_model: {
      assumptions: {
        targetGrossMargin: 0.7,
        overheadReserve: 0.1,
        aiUnitCostUsd: 0.01,
        egressCostPerGb: 0.085,
        projectStorageCostPerGbMonth: 0.15,
        blobStorageCostPerGbMonth: 0.015,
        rootfsStorageCostPerGbMonth: 0.04,
        spotCpuCostPerMonth: 6,
        spotRamGbCostPerMonth: 1,
        standardCpuCostPerMonth: 25,
        standardRamGbCostPerMonth: 3.5,
        averageCpuUtilization: 0.5,
        averageRamUtilization: 0.5,
        sharedHostUsableRamGb: 48,
        sharedHostUsableVcpu: 16,
        targetRamOversubscription: 1.5,
        targetCpuOversubscription: 8,
        activeProjectConcurrency: 1,
      },
      expected_usage: {
        aiUnits7d: 0,
        egress7dGb: 0,
        projectStorageHardCapGb: 5,
        blobStorageGb: 0.1,
        rootfsStorageGb: 0,
        spotCpuHoursMonthly: 25,
        spotRamGbHoursMonthly: 100,
        standardCpuHoursMonthly: 0,
        standardRamGbHoursMonthly: 0,
      },
    },
    disabled: false,
    notes: "bootstrap admin tier",
  },
  basic: {
    id: "basic",
    label: "Basic",
    store_visible: false,
    store_description: "For occasional light use.",
    store_highlights: ["More shared resources", "Access better shared hosts"],
    site_license_pool_description: "Light CoCalc access for occasional work.",
    team_visible: false,
    course_store_visible: false,
    course_allowed_domains: [],
    priority: 10,
    price_monthly: 8,
    price_yearly: 72,
    trial_days: null,
    project_defaults: {
      disk_quota: 10000,
      memory: 4000,
      memory_request: 0,
    },
    ai_limits: {
      units_5h: 0,
      units_7d: 0,
    },
    features: {
      create_hosts: false,
      project_host_tier: 0,
    },
    usage_limits: {
      shared_compute_priority: 1,
      max_sponsored_running_projects: 3,
      notification_email_send_limit_5h: 50,
      notification_email_send_limit_7d: 200,
      cpu_5h_seconds: 72000,
      cpu_7d_seconds: 540000,
      max_projects: 10,
      total_storage_soft_bytes: 13000000000,
      total_storage_hard_bytes: 15000000000,
      acp_max_queued_per_account: 100,
      acp_max_queued_per_thread: 20,
      acp_max_created_5h_per_account: 100,
      acp_max_created_7d_per_account: 500,
      acp_max_running_per_account: 5,
      acp_max_running_per_project: 2,
      acp_max_active_automations_per_project: 3,
      rootfs_count: 0,
      rootfs_total_storage_gb: 0,
      rootfs_max_storage_gb: 0,
      rootfs_oci_images: false,
      blob_account_total_bytes: 1000000000,
      blob_account_count: 1000,
      blob_project_total_bytes: 500000000,
      blob_project_count: 500,
      invite_email_send_enabled: false,
      invite_email_daily_count: 20,
      invite_email_hourly_count: 10,
      invite_email_recipients_per_batch: 10,
      invite_email_pending_per_project: 25,
      invite_email_pending_per_course: 50,
      invite_email_resend_cooldown_minutes: 15,
      invite_email_custom_message_max_chars: 300,
      invite_email_allow_project_title: false,
      invite_email_allow_course_title: false,
      invite_email_allow_urls: false,
      invite_email_link_copy_enabled: true,
      project_max_collaborators_and_pending_invites: 25,
      course_max_students_and_pending_invites: 50,
      egress_5h_bytes: 4000000000,
      egress_7d_bytes: 7500000000,
      max_backups_per_project: 10,
      max_snapshots_per_project: 10,
    },
    pricing_model: {
      assumptions: {
        targetGrossMargin: 0.7,
        overheadReserve: 0.1,
        aiUnitCostUsd: 0.01,
        egressCostPerGb: 0.085,
        projectStorageCostPerGbMonth: 0.1,
        blobStorageCostPerGbMonth: 0.015,
        rootfsStorageCostPerGbMonth: 0.04,
        spotCpuCostPerMonth: 6,
        spotRamGbCostPerMonth: 1,
        standardCpuCostPerMonth: 25,
        standardRamGbCostPerMonth: 3.5,
        averageCpuUtilization: 0.5,
        averageRamUtilization: 0.5,
        sharedHostUsableRamGb: 48,
        sharedHostUsableVcpu: 16,
        targetRamOversubscription: 1.5,
        targetCpuOversubscription: 8,
        activeProjectConcurrency: 1,
      },
      expected_usage: {
        aiUnits7d: 0,
        egress7dGb: 0,
        projectStorageHardCapGb: 5,
        blobStorageGb: 0.1,
        rootfsStorageGb: 0,
        spotCpuHoursMonthly: 25,
        spotRamGbHoursMonthly: 100,
        standardCpuHoursMonthly: 0,
        standardRamGbHoursMonthly: 0,
      },
    },
    disabled: false,
    notes: null,
  },
  free: {
    id: "free",
    label: "Free",
    store_visible: false,
    store_description:
      "Start using CoCalc with just enough resources to explore the platform and do basic work.",
    store_highlights: [],
    site_license_pool_description:
      "Basic CoCalc access for evaluation and occasional use.",
    team_visible: false,
    course_store_visible: false,
    course_allowed_domains: [],
    priority: 0,
    price_monthly: 0,
    price_yearly: 0,
    trial_days: 0,
    project_defaults: {
      disk_quota: 4000,
      memory: 2000,
      memory_request: 0,
    },
    ai_limits: {
      units_5h: 0,
      units_7d: 0,
    },
    features: {
      create_hosts: false,
      project_host_tier: 0,
    },
    usage_limits: {
      shared_compute_priority: 0,
      max_sponsored_running_projects: 1,
      notification_email_send_limit_5h: 10,
      notification_email_send_limit_7d: 40,
      cpu_5h_seconds: 10800,
      cpu_7d_seconds: 72000,
      max_projects: 5,
      total_storage_soft_bytes: 7000000000,
      total_storage_hard_bytes: 8000000000,
      acp_max_queued_per_account: 20,
      acp_max_queued_per_thread: 5,
      acp_max_created_5h_per_account: 20,
      acp_max_created_7d_per_account: 100,
      acp_max_running_per_account: 3,
      acp_max_running_per_project: 2,
      acp_max_active_automations_per_project: 0,
      rootfs_count: 0,
      rootfs_total_storage_gb: 0,
      rootfs_max_storage_gb: 0,
      rootfs_oci_images: false,
      blob_account_total_bytes: 250000000,
      blob_account_count: 200,
      blob_project_total_bytes: 250000000,
      blob_project_count: 100,
      invite_email_send_enabled: false,
      invite_email_daily_count: 10,
      invite_email_hourly_count: 5,
      invite_email_recipients_per_batch: 5,
      invite_email_pending_per_project: 10,
      invite_email_pending_per_course: 10,
      invite_email_resend_cooldown_minutes: 15,
      invite_email_custom_message_max_chars: 300,
      invite_email_allow_project_title: false,
      invite_email_allow_course_title: false,
      invite_email_allow_urls: false,
      invite_email_link_copy_enabled: true,
      project_max_collaborators_and_pending_invites: 10,
      course_max_students_and_pending_invites: 10,
      egress_5h_bytes: 2000000000,
      egress_7d_bytes: 3500000000,
      max_backups_per_project: 4,
      credit_spend_limit_5h_usd: 0,
      credit_spend_limit_7d_usd: 0,
      max_snapshots_per_project: 7,
      prepaid_host_usage_limit_5h_usd: 0,
      prepaid_host_usage_limit_7d_usd: 0,
    },
    pricing_model: {
      assumptions: {
        targetGrossMargin: 0.7,
        overheadReserve: 0.1,
        aiUnitCostUsd: 0.01,
        egressCostPerGb: 0.085,
        projectStorageCostPerGbMonth: 0.1,
        blobStorageCostPerGbMonth: 0.015,
        rootfsStorageCostPerGbMonth: 0.04,
        spotCpuCostPerMonth: 6,
        spotRamGbCostPerMonth: 1,
        standardCpuCostPerMonth: 25,
        standardRamGbCostPerMonth: 3.5,
        averageCpuUtilization: 0.5,
        averageRamUtilization: 0.5,
        sharedHostUsableRamGb: 48,
        sharedHostUsableVcpu: 16,
        targetRamOversubscription: 1.5,
        targetCpuOversubscription: 8,
        activeProjectConcurrency: 1,
      },
      expected_usage: {
        aiUnits7d: 0,
        egress7dGb: 0,
        projectStorageHardCapGb: 2,
        blobStorageGb: 0.05,
        rootfsStorageGb: 0,
        spotCpuHoursMonthly: 10,
        spotRamGbHoursMonthly: 10,
        standardCpuHoursMonthly: 0,
        standardRamGbHoursMonthly: 0,
      },
    },
    disabled: false,
    notes: "",
  },
  instructor: {
    id: "instructor",
    label: "Instructor",
    store_visible: false,
    store_description:
      "For instructors managing courses, larger classes, and many collaborators.",
    store_highlights: [
      "Higher project and storage limits",
      "Course-scale invitation limits",
      "More room for teaching workflows",
    ],
    site_license_pool_description:
      "Teaching-focused CoCalc access for instructors and course staff.",
    team_visible: false,
    course_store_visible: false,
    course_allowed_domains: [],
    priority: 25,
    price_monthly: 75,
    price_yearly: 675,
    project_defaults: {
      disk_quota: 30000,
      memory: 12000,
      memory_request: 0,
    },
    ai_limits: {
      units_5h: 0,
      units_7d: 0,
    },
    features: {
      create_hosts: true,
      project_host_tier: 1,
    },
    usage_limits: {
      shared_compute_priority: 2,
      max_sponsored_running_projects: 25,
      notification_email_send_limit_5h: 500,
      notification_email_send_limit_7d: 2500,
      cpu_5h_seconds: 1080000,
      cpu_7d_seconds: 3600000,
      max_projects: 1000,
      prepaid_host_usage_limit_5h_usd: 500,
      prepaid_host_usage_limit_7d_usd: 3000,
      acp_max_queued_per_account: 250,
      acp_max_queued_per_thread: 50,
      acp_max_created_5h_per_account: 250,
      acp_max_created_7d_per_account: 1000,
      acp_max_running_per_account: 25,
      acp_max_running_per_project: 10,
      acp_max_active_automations_per_project: 10,
      rootfs_count: 50,
      rootfs_total_storage_gb: 75,
      rootfs_max_storage_gb: 20,
      rootfs_oci_images: false,
      blob_account_total_bytes: 15000000000,
      blob_account_count: 20000,
      blob_project_total_bytes: 2000000000,
      blob_project_count: 2000,
      invite_email_send_enabled: true,
      invite_email_daily_count: 500,
      invite_email_hourly_count: 200,
      invite_email_recipients_per_batch: 200,
      invite_email_pending_per_project: 250,
      invite_email_pending_per_course: 500,
      invite_email_resend_cooldown_minutes: 15,
      invite_email_custom_message_max_chars: 600,
      invite_email_allow_project_title: true,
      invite_email_allow_course_title: true,
      invite_email_allow_urls: false,
      invite_email_link_copy_enabled: true,
      project_max_collaborators_and_pending_invites: 250,
      course_max_students_and_pending_invites: 500,
      egress_5h_bytes: 20000000000,
      egress_7d_bytes: 50000000000,
      max_backups_per_project: 10,
      total_storage_hard_bytes: 300000000000,
      total_storage_soft_bytes: 250000000000,
      credit_spend_limit_5h_usd: 1000,
      credit_spend_limit_7d_usd: 5000,
      max_snapshots_per_project: 20,
    },
    pricing_model: {
      assumptions: {
        targetGrossMargin: 0.7,
        overheadReserve: 0.1,
        aiUnitCostUsd: 0.01,
        egressCostPerGb: 0.085,
        projectStorageCostPerGbMonth: 0.1,
        blobStorageCostPerGbMonth: 0.015,
        rootfsStorageCostPerGbMonth: 0.04,
        spotCpuCostPerMonth: 6,
        spotRamGbCostPerMonth: 1,
        standardCpuCostPerMonth: 25,
        standardRamGbCostPerMonth: 3.5,
        averageCpuUtilization: 0.5,
        averageRamUtilization: 0.5,
        sharedHostUsableRamGb: 48,
        sharedHostUsableVcpu: 16,
        targetRamOversubscription: 1.5,
        targetCpuOversubscription: 8,
        activeProjectConcurrency: 1,
      },
      expected_usage: {
        aiUnits7d: 0,
        egress7dGb: 0,
        projectStorageHardCapGb: 5,
        blobStorageGb: 0.1,
        rootfsStorageGb: 0,
        spotCpuHoursMonthly: 25,
        spotRamGbHoursMonthly: 100,
        standardCpuHoursMonthly: 0,
        standardRamGbHoursMonthly: 0,
      },
    },
    disabled: false,
    notes:
      "This is meant to be provided FOR FREE to instructors who will using student-pay or institute pay after we connect with them. ",
  },
  standard: {
    id: "standard",
    label: "Standard",
    store_visible: false,
    store_description: "A solid choice for everyday work.",
    store_highlights: [
      "Higher priority",
      "More backups, snapshots, projects and collaborators.",
      "Purchase pay as you go dedicated VMs.",
    ],
    site_license_pool_description: null,
    team_visible: false,
    course_store_visible: false,
    course_allowed_domains: [],
    priority: 20,
    price_monthly: 24,
    price_yearly: 216,
    trial_days: 7,
    course_price: null,
    course_duration_days: null,
    course_grace_days: null,
    project_defaults: {
      memory: 8000,
      disk_quota: 16000,
      memory_request: 0,
    },
    ai_limits: {
      units_5h: 0,
      units_7d: 0,
    },
    features: {
      create_hosts: true,
      project_host_tier: 1,
    },
    usage_limits: {
      max_projects: 20,
      rootfs_count: 20,
      cpu_5h_seconds: 180000,
      cpu_7d_seconds: 1080000,
      egress_5h_bytes: 5000000000,
      egress_7d_bytes: 20000000000,
      rootfs_oci_images: false,
      blob_account_count: 5000,
      blob_project_count: 1000,
      rootfs_max_storage_gb: 10,
      invite_email_allow_urls: false,
      max_backups_per_project: 20,
      rootfs_total_storage_gb: 25,
      shared_compute_priority: 2,
      blob_account_total_bytes: 5000000000,
      blob_project_total_bytes: 1000000000,
      invite_email_daily_count: 50,
      total_storage_hard_bytes: 50000000000,
      total_storage_soft_bytes: 45000000000,
      invite_email_hourly_count: 20,
      invite_email_send_enabled: true,
      max_snapshots_per_project: 30,
      invite_email_link_copy_enabled: true,
      max_sponsored_running_projects: 3,
      invite_email_allow_course_title: true,
      invite_email_pending_per_course: 100,
      prepaid_host_usage_limit_5h_usd: 100,
      prepaid_host_usage_limit_7d_usd: 1000,
      invite_email_allow_project_title: true,
      invite_email_pending_per_project: 50,
      notification_email_send_limit_5h: 200,
      notification_email_send_limit_7d: 1000,
      invite_email_recipients_per_batch: 25,
      invite_email_resend_cooldown_minutes: 15,
      invite_email_custom_message_max_chars: 600,
      course_max_students_and_pending_invites: 100,
      project_max_collaborators_and_pending_invites: 50,
    },
    pricing_model: {
      assumptions: {
        targetGrossMargin: 0.7,
        overheadReserve: 0.1,
        aiUnitCostUsd: 0.01,
        egressCostPerGb: 0.085,
        projectStorageCostPerGbMonth: 0.1,
        blobStorageCostPerGbMonth: 0.015,
        rootfsStorageCostPerGbMonth: 0.04,
        spotCpuCostPerMonth: 6,
        spotRamGbCostPerMonth: 1,
        standardCpuCostPerMonth: 25,
        standardRamGbCostPerMonth: 3.5,
        averageCpuUtilization: 0.5,
        averageRamUtilization: 0.5,
        sharedHostUsableRamGb: 48,
        sharedHostUsableVcpu: 16,
        targetRamOversubscription: 1.5,
        targetCpuOversubscription: 8,
        activeProjectConcurrency: 1,
      },
      expected_usage: {
        aiUnits7d: 0,
        egress7dGb: 5,
        projectStorageHardCapGb: 100,
        blobStorageGb: 1,
        rootfsStorageGb: 30,
        spotCpuHoursMonthly: 50,
        spotRamGbHoursMonthly: 200,
        standardCpuHoursMonthly: 20,
        standardRamGbHoursMonthly: 100,
      },
    },
    disabled: false,
    notes: "",
  },
  pro: {
    id: "pro",
    label: "Pro",
    store_visible: false,
    store_description: "For advanced users and researchers",
    store_highlights: [
      "Best shared resources",
      "Many running projects and agent automations at once",
      "Pay at the end of the month for powerful dedicated VMs",
    ],
    site_license_pool_description:
      "Advanced CoCalc access for demanding projects.",
    team_visible: false,
    course_store_visible: false,
    course_allowed_domains: [],
    priority: 30,
    price_monthly: 200,
    price_yearly: 1800,
    trial_days: 0,
    project_defaults: {
      disk_quota: 40000,
      memory: 16000,
      memory_request: 250,
    },
    ai_limits: {
      units_5h: 0,
      units_7d: 0,
    },
    features: {
      create_hosts: true,
      project_host_tier: 2,
    },
    usage_limits: {
      shared_compute_priority: 4,
      max_sponsored_running_projects: 16,
      notification_email_send_limit_5h: 1000,
      notification_email_send_limit_7d: 5000,
      cpu_5h_seconds: 3600000,
      cpu_7d_seconds: 18000000,
      max_projects: 250,
      total_storage_soft_bytes: 450000000000,
      total_storage_hard_bytes: 500000000000,
      credit_spend_limit_5h_usd: 200,
      credit_spend_limit_7d_usd: 1000,
      prepaid_host_usage_limit_5h_usd: 2000,
      prepaid_host_usage_limit_7d_usd: 8000,
      acp_max_queued_per_account: 500,
      acp_max_queued_per_thread: 100,
      acp_max_created_5h_per_account: 500,
      acp_max_created_7d_per_account: 2000,
      acp_max_running_per_account: 50,
      acp_max_running_per_project: 20,
      acp_max_active_automations_per_project: 20,
      rootfs_count: 250,
      rootfs_total_storage_gb: 250,
      rootfs_max_storage_gb: 30,
      rootfs_oci_images: true,
      blob_account_total_bytes: 25000000000,
      blob_account_count: 50000,
      blob_project_total_bytes: 5000000000,
      blob_project_count: 5000,
      invite_email_send_enabled: true,
      invite_email_daily_count: 1000,
      invite_email_hourly_count: 500,
      invite_email_recipients_per_batch: 500,
      invite_email_pending_per_project: 500,
      invite_email_pending_per_course: 1000,
      invite_email_resend_cooldown_minutes: 15,
      invite_email_custom_message_max_chars: 1000,
      invite_email_allow_project_title: true,
      invite_email_allow_course_title: true,
      invite_email_allow_urls: false,
      invite_email_link_copy_enabled: true,
      project_max_collaborators_and_pending_invites: 500,
      course_max_students_and_pending_invites: 1000,
      egress_5h_bytes: 20000000000,
      egress_7d_bytes: 100000000000,
      max_backups_per_project: 15,
      max_snapshots_per_project: 20,
    },
    pricing_model: {
      assumptions: {
        targetGrossMargin: 0.7,
        overheadReserve: 0.1,
        aiUnitCostUsd: 0.01,
        egressCostPerGb: 0.085,
        projectStorageCostPerGbMonth: 0.1,
        blobStorageCostPerGbMonth: 0.015,
        rootfsStorageCostPerGbMonth: 0.04,
        spotCpuCostPerMonth: 6,
        spotRamGbCostPerMonth: 1,
        standardCpuCostPerMonth: 25,
        standardRamGbCostPerMonth: 3.5,
        averageCpuUtilization: 0.5,
        averageRamUtilization: 0.5,
        sharedHostUsableRamGb: 48,
        sharedHostUsableVcpu: 16,
        targetRamOversubscription: 1.5,
        targetCpuOversubscription: 8,
        activeProjectConcurrency: 1,
      },
      expected_usage: {
        aiUnits7d: 0,
        egress7dGb: 5,
        projectStorageHardCapGb: 100,
        blobStorageGb: 1,
        rootfsStorageGb: 30,
        spotCpuHoursMonthly: 50,
        spotRamGbHoursMonthly: 200,
        standardCpuHoursMonthly: 20,
        standardRamGbHoursMonthly: 100,
      },
    },
    disabled: false,
    notes: "",
  },
  student: {
    id: "student",
    label: "Student",
    store_visible: false,
    store_description:
      "A term-length membership for students who need course access without a recurring subscription.",
    store_highlights: [
      "One-time course payment",
      "Resources for class projects",
      "Access throughout the academic term",
    ],
    site_license_pool_description: "Course-focused CoCalc access for students.",
    team_visible: false,
    course_store_visible: false,
    course_allowed_domains: [],
    priority: 10,
    price_monthly: 8,
    price_yearly: 72,
    course_price: 18,
    course_duration_days: 122,
    course_grace_days: 10,
    project_defaults: {
      disk_quota: 10000,
      memory: 8000,
      memory_request: 0,
    },
    ai_limits: {
      units_5h: 0,
      units_7d: 0,
    },
    features: {
      create_hosts: false,
      project_host_tier: 1,
    },
    usage_limits: {
      shared_compute_priority: 1,
      max_sponsored_running_projects: 3,
      notification_email_send_limit_5h: 50,
      notification_email_send_limit_7d: 200,
      cpu_5h_seconds: 90000,
      cpu_7d_seconds: 540000,
      acp_max_queued_per_account: 100,
      acp_max_queued_per_thread: 20,
      acp_max_created_5h_per_account: 100,
      acp_max_created_7d_per_account: 500,
      acp_max_running_per_account: 3,
      acp_max_running_per_project: 2,
      acp_max_active_automations_per_project: 2,
      rootfs_count: 0,
      rootfs_total_storage_gb: 0,
      rootfs_max_storage_gb: 0,
      rootfs_oci_images: false,
      blob_account_total_bytes: 1000000000,
      blob_account_count: 1000,
      blob_project_total_bytes: 500000000,
      blob_project_count: 500,
      invite_email_send_enabled: false,
      invite_email_daily_count: 20,
      invite_email_hourly_count: 10,
      invite_email_recipients_per_batch: 10,
      invite_email_pending_per_project: 25,
      invite_email_pending_per_course: 50,
      invite_email_resend_cooldown_minutes: 15,
      invite_email_custom_message_max_chars: 300,
      invite_email_allow_project_title: false,
      invite_email_allow_course_title: false,
      invite_email_allow_urls: false,
      invite_email_link_copy_enabled: true,
      project_max_collaborators_and_pending_invites: 25,
      course_max_students_and_pending_invites: 50,
      max_projects: 10,
      egress_5h_bytes: 3000000000,
      egress_7d_bytes: 5000000000,
      max_backups_per_project: 10,
      total_storage_hard_bytes: 15000000000,
      total_storage_soft_bytes: 13000000000,
      max_snapshots_per_project: 10,
    },
    pricing_model: {
      assumptions: {
        targetGrossMargin: 0.7,
        overheadReserve: 0.1,
        aiUnitCostUsd: 0.01,
        egressCostPerGb: 0.085,
        projectStorageCostPerGbMonth: 0.1,
        blobStorageCostPerGbMonth: 0.015,
        rootfsStorageCostPerGbMonth: 0.04,
        spotCpuCostPerMonth: 6,
        spotRamGbCostPerMonth: 1,
        standardCpuCostPerMonth: 25,
        standardRamGbCostPerMonth: 3.5,
        averageCpuUtilization: 0.5,
        averageRamUtilization: 0.5,
        sharedHostUsableRamGb: 48,
        sharedHostUsableVcpu: 16,
        targetRamOversubscription: 1.5,
        targetCpuOversubscription: 8,
        activeProjectConcurrency: 1,
      },
      expected_usage: {
        aiUnits7d: 0,
        egress7dGb: 0,
        projectStorageHardCapGb: 5,
        blobStorageGb: 0.1,
        rootfsStorageGb: 0,
        spotCpuHoursMonthly: 25,
        spotRamGbHoursMonthly: 100,
        standardCpuHoursMonthly: 0,
        standardRamGbHoursMonthly: 0,
      },
    },
    disabled: false,
    notes: null,
  },
} as const;

export function getTierTemplate(id: keyof typeof TIER_TEMPLATES) {
  return TIER_TEMPLATES[id];
}

type TierTemplateFields = {
  id?: string;
  label?: string;
  store_visible?: boolean;
  store_description?: string | null;
  store_highlights?: readonly string[];
  site_license_pool_description?: string | null;
  team_visible?: boolean;
  course_store_visible?: boolean;
  course_allowed_domains?: readonly string[] | null;
  course_price?: number | null;
  course_duration_days?: number | null;
  course_grace_days?: number | null;
  priority?: number;
  price_monthly?: number;
  price_yearly?: number;
  trial_days?: number | null;
  project_defaults?: Record<string, unknown>;
  ai_limits?: Record<string, unknown>;
  features?: Record<string, unknown>;
  usage_limits?: unknown;
  pricing_model?: unknown;
  disabled?: boolean;
  notes?: string | null;
};

function mergeTemplateObject(
  templateValue: unknown,
  tierValue: unknown,
): unknown {
  if (
    templateValue != null &&
    typeof templateValue === "object" &&
    !Array.isArray(templateValue) &&
    tierValue != null &&
    typeof tierValue === "object" &&
    !Array.isArray(tierValue)
  ) {
    return {
      ...(templateValue as Record<string, unknown>),
      ...(tierValue as Record<string, unknown>),
    };
  }
  return tierValue ?? templateValue;
}

export function applyMembershipTierTemplateFallbacks<
  T extends TierTemplateFields,
>(tier: T): T {
  const template = TIER_TEMPLATES[tier.id as keyof typeof TIER_TEMPLATES];
  if (template == null) return tier;
  const templateFields = template as TierTemplateFields;
  return {
    ...tier,
    label: tier.label ?? template.label,
    store_visible: tier.store_visible ?? template.store_visible,
    store_description:
      tier.store_description ?? templateFields.store_description,
    store_highlights:
      tier.store_highlights ??
      (templateFields.store_highlights == null
        ? undefined
        : [...templateFields.store_highlights]),
    site_license_pool_description:
      tier.site_license_pool_description ??
      templateFields.site_license_pool_description,
    team_visible: tier.team_visible ?? templateFields.team_visible,
    course_store_visible:
      tier.course_store_visible ?? template.course_store_visible,
    course_allowed_domains:
      tier.course_allowed_domains ??
      (templateFields.course_allowed_domains == null
        ? undefined
        : [...templateFields.course_allowed_domains]),
    course_price: tier.course_price ?? templateFields.course_price,
    course_duration_days:
      tier.course_duration_days ?? templateFields.course_duration_days,
    course_grace_days:
      tier.course_grace_days ?? templateFields.course_grace_days,
    priority: tier.priority ?? template.priority,
    price_monthly: tier.price_monthly ?? template.price_monthly,
    price_yearly: tier.price_yearly ?? template.price_yearly,
    trial_days: tier.trial_days ?? templateFields.trial_days,
    disabled: tier.disabled ?? templateFields.disabled,
    notes: tier.notes ?? templateFields.notes,
    pricing_model: mergeTemplateObject(
      templateFields.pricing_model,
      tier.pricing_model,
    ),
    project_defaults: mergeTemplateObject(
      template.project_defaults,
      tier.project_defaults,
    ),
    ai_limits: mergeTemplateObject(template.ai_limits, tier.ai_limits),
    features: mergeTemplateObject(template.features, tier.features),
    usage_limits: mergeTemplateObject(template.usage_limits, tier.usage_limits),
  };
}
