/*
 *  This file is part of CoCalc: Copyright © 2026 Sagemath, Inc.
 *  License: MS-RSL – see LICENSE.md for details
 */

import type { DocsEntry } from "./types";
import {
  docsIcon,
  projectActionParameters,
  projectHostActionParameters,
} from "./helpers";
import {
  PROJECT_SECRETS_BODY,
  OPEN_TERMINAL_BODY,
  USE_TERMINAL_BODY,
  CREATE_JUPYTER_BODY,
  USE_JUPYTER_BODY,
  JUPYTER_KERNEL_TERMINATED_BODY,
  CUSTOM_JUPYTER_KERNELS_BODY,
  ROOTFS_BODY,
  MEMORY_TROUBLESHOOTING_BODY,
  CONNECTIVITY_TROUBLESHOOTING_BODY,
  COLLABORATORS_BODY,
  CHAT_BODY,
  MENTIONS_BODY,
  TIMETRAVEL_BODY,
  COURSE_ASSIGNMENT_BODY,
  COURSE_WORKFLOW_BODY,
  NBGRADER_BODY,
  CODEX_CHAT_BODY,
  CREATE_PROJECT_BODY,
  AI_CREDENTIALS_BODY,
  COCALC_CLI_BODY,
  HTTP_API_BODY,
  PROJECT_HOSTS_BODY,
  PROJECT_HOST_ACCESS_BODY,
  PROJECT_HOST_MOVE_BODY,
  PROJECT_HOST_LIFECYCLE_BODY,
  PROJECT_HOST_SPOT_RECOVERY_BODY,
  PROJECT_HOST_CHANGE_RULES_BODY,
  PROJECT_HOST_RELIABILITY_BODY,
  PROJECT_HOST_SOFTWARE_LIFECYCLE_BODY,
  PROJECT_HOST_STORAGE_BODY,
  PROJECT_HOST_SHARED_SCRATCH_BODY,
  PROJECT_HOST_LOGS_BODY,
  PROJECT_FILES_BODY,
  MARKDOWN_BODY,
  LATEX_BODY,
  R_MARKDOWN_BODY,
  TASKS_BODY,
  SLIDES_BODY,
  WHITEBOARD_BODY,
  FILE_EXPLORER_BODY,
  PROJECT_LIST_BODY,
  GIT_BODY,
  PYTHON_BODY,
  DOCS_BROWSER_BODY,
  DOCS_ACTIONS_BODY,
  BROWSER_AUTOMATION_BODY,
  ADMIN_OVERVIEW_BODY,
  ADMIN_NEWS_BODY,
  ADMIN_SITE_SETTINGS_BODY,
  ADMIN_USERS_BODY,
  ADMIN_CLI_BODY,
  ADMIN_BAY_OPS_BODY,
  ADMIN_ROOTFS_BODY,
  ADMIN_BACKUP_SHARDS_BODY,
  ADMIN_REGISTRATION_TOKENS_BODY,
  ADMIN_MEMBERSHIP_AND_LICENSES_BODY,
  ADMIN_MANAGED_EGRESS_BODY,
  ADMIN_SSO_BODY,
} from "./content";

export const DOCS_ENTRIES: DocsEntry[] = [
  {
    audiences: ["agents", "teams"],
    body: ADMIN_OVERVIEW_BODY.trim(),
    category: "Admin",
    id: "admin.overview",
    image: docsIcon(
      "/public/docs/browser-automation-5dc255b9.webp",
      "Admin tools connected to operational checks and site controls",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/overview",
    status: "ready",
    summary:
      "Understand the admin docs surface and the safety model for site operations.",
    title: "Admin operations overview",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> News manager.",
        executable: true,
        id: "admin.news.open",
        label: "Open news manager",
      },
      {
        description: "Open the Admin -> News editor for a new system notice.",
        executable: true,
        id: "admin.news.create-system",
        label: "Create system notice",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_NEWS_BODY.trim(),
    category: "Admin",
    id: "admin.news",
    image: docsIcon(
      "/public/docs/docs-browser-74a65d58.webp",
      "A site-wide message card prepared for CoCalc users",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/news",
    status: "ready",
    summary:
      "Create public news, events, and in-app system notices for a CoCalc site.",
    title: "Manage news and system notices",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> Site Settings section.",
        executable: true,
        id: "admin.site-settings.open",
        label: "Open site settings",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_SITE_SETTINGS_BODY.trim(),
    category: "Admin",
    id: "admin.site-settings",
    image: docsIcon(
      "/public/docs/runtime-image-09add8c9.webp",
      "Site configuration controls with cloud and runtime settings",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/site-settings",
    status: "ready",
    summary:
      "Use the admin site settings section and configuration wizards safely.",
    title: "Configure site settings",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> User Search section.",
        executable: true,
        id: "admin.users.open",
        label: "Open user search",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_USERS_BODY.trim(),
    category: "Admin",
    id: "admin.users",
    image: docsIcon(
      "/public/docs/collaborators-8ce1955f.webp",
      "Admin user cards with account support controls",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/users",
    status: "ready",
    summary:
      "Find accounts and use impersonation, password reset, 2FA removal, ban, project, and billing tools.",
    title: "Manage users as an admin",
    visibility: "admin",
  },
  {
    audiences: ["agents", "teams"],
    body: ADMIN_CLI_BODY.trim(),
    category: "Admin",
    id: "admin.cocalc-cli",
    image: docsIcon(
      "/public/docs/cocalc-cli-862b8d4e.webp",
      "An admin terminal inspecting bays, accounts, and project hosts",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/cocalc-cli",
    status: "ready",
    summary:
      "Use cocalc-cli for admin inspection, fresh auth, bay listing, account location, and rehome smoke tests.",
    title: "Admin cocalc-cli cookbook",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> Bay Operations section.",
        executable: true,
        id: "admin.bay-ops.open",
        label: "Open bay operations",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_BAY_OPS_BODY.trim(),
    category: "Admin",
    id: "admin.bay-ops",
    image: docsIcon(
      "/public/docs/browser-automation-5dc255b9.webp",
      "Bay operation status with ownership and rehome checks",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/bay-ops",
    status: "ready",
    summary:
      "Inspect bay health, ownership counts, rehome operations, backup health, and load projections.",
    title: "Inspect bay operations",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> RootFS Images section.",
        executable: true,
        id: "admin.rootfs.open",
        label: "Open RootFS images",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_ROOTFS_BODY.trim(),
    category: "Admin",
    id: "admin.rootfs",
    image: docsIcon(
      "/public/docs/runtime-image-09add8c9.webp",
      "Runtime image catalog entries cached across project hosts",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/rootfs",
    status: "ready",
    summary:
      "Manage runtime image catalog entries, host scans, visibility, blocking, deletion, and retention.",
    title: "Administer RootFS images",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> Backup Shards section.",
        executable: true,
        id: "admin.project-backup-shards.open",
        label: "Open backup shards",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_BACKUP_SHARDS_BODY.trim(),
    category: "Admin",
    id: "admin.project-backup-shards",
    image: docsIcon(
      "/public/docs/project-files-6c4ff552.webp",
      "Backup shard storage routes connected to project folders",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/project-backup-shards",
    status: "ready",
    summary:
      "Inspect project backup shard configuration and connect shard health to bay operations.",
    title: "Review backup shards",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> Registration Tokens section.",
        executable: true,
        id: "admin.registration-tokens.open",
        label: "Open registration tokens",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_REGISTRATION_TOKENS_BODY.trim(),
    category: "Admin",
    id: "admin.registration-tokens",
    image: docsIcon(
      "/public/docs/project-secrets-ea9872ae.webp",
      "A registration token card granting controlled site access",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/registration-tokens",
    status: "ready",
    summary:
      "Create and review targeted signup tokens for cohorts, classrooms, pilots, and restricted sites.",
    title: "Manage registration tokens",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> Membership Tiers section.",
        executable: true,
        id: "admin.membership-tiers.open",
        label: "Open membership tiers",
      },
      {
        description: "Open the Admin -> Software Licenses section.",
        executable: true,
        id: "admin.software-licenses.open",
        label: "Open software licenses",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_MEMBERSHIP_AND_LICENSES_BODY.trim(),
    category: "Admin",
    id: "admin.membership-licenses",
    image: docsIcon(
      "/public/docs/project-hosts-684faa4c.webp",
      "Membership and license controls for account capabilities",
    ),
    lastReviewed: "2026-05-26",
    slug: "admin/membership-licenses",
    status: "ready",
    summary:
      "Understand membership tiers, software licenses, dedicated-host limits, and commercial access policies.",
    title: "Manage membership and licenses",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> Network Egress section.",
        executable: true,
        id: "admin.managed-egress.open",
        label: "Open network egress",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_MANAGED_EGRESS_BODY.trim(),
    category: "Admin",
    id: "admin.managed-egress",
    image: docsIcon(
      "/public/docs/connectivity-eaca154f.webp",
      "Network egress activity grouped by accounts, projects, and categories",
    ),
    lastReviewed: "2026-05-27",
    slug: "admin/managed-egress",
    status: "ready",
    summary:
      "Use the admin Network Egress overview to investigate recent account, project, and category network usage.",
    title: "Monitor network egress",
    visibility: "admin",
  },
  {
    actions: [
      {
        description: "Open the Admin -> SSO Providers & Domains section.",
        executable: true,
        id: "admin.sso.open",
        label: "Open SSO settings",
      },
    ],
    audiences: ["agents", "teams"],
    body: ADMIN_SSO_BODY.trim(),
    category: "Admin",
    id: "admin.sso",
    image: docsIcon(
      "/public/docs/http-api-5067e8ed.webp",
      "An identity provider connection with domain policy controls",
    ),
    lastReviewed: "2026-05-27",
    slug: "admin/sso",
    status: "ready",
    summary:
      "Configure SSO providers and domain policies without locking users out.",
    title: "Configure SSO providers and domains",
    visibility: "admin",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: CREATE_PROJECT_BODY.trim(),
    category: "Projects",
    id: "projects.create-project",
    image: docsIcon(
      "/public/docs/create-project-5b221552.webp",
      "A new CoCalc project folder with notebook, terminal, and chat tools",
    ),
    lastReviewed: "2026-05-24",
    slug: "projects/create-project",
    status: "ready",
    summary:
      "Create a durable Linux workspace for files, notebooks, terminals, chat, and agents.",
    title: "Create a project",
  },
  {
    actions: [
      {
        description:
          "Open the project Settings -> Environment -> Secrets panel.",
        executable: true,
        id: "settings.environment.secrets",
        label: "Open project secrets",
        parameters: projectActionParameters(),
      },
    ],
    audiences: ["agents", "researchers", "students", "teams"],
    body: PROJECT_SECRETS_BODY.trim(),
    category: "Projects",
    id: "projects.project-secrets",
    image: docsIcon(
      "/public/docs/project-secrets-ea9872ae.webp",
      "Project secrets mounted as protected read-only files",
    ),
    lastReviewed: "2026-05-24",
    slug: "projects/project-secrets",
    status: "ready",
    summary:
      "Store API keys and credentials as encrypted, read-only files mounted into the running project.",
    title: "Project secrets",
  },
  {
    audiences: ["agents", "researchers", "students", "teams"],
    body: AI_CREDENTIALS_BODY.trim(),
    category: "AI",
    id: "ai.connect-credentials",
    image: docsIcon(
      "/public/docs/connect-ai-access-522e86e1.webp",
      "AI access connected securely to a CoCalc project",
    ),
    lastReviewed: "2026-05-24",
    slug: "ai/connect-credentials",
    status: "ready",
    summary: "Connect ChatGPT or OpenAI API access for Codex and project code.",
    title: "Connect AI access",
  },
  {
    audiences: ["agents", "researchers", "teams"],
    body: COCALC_CLI_BODY.trim(),
    category: "CLI",
    id: "cli.use-cocalc-cli",
    image: docsIcon(
      "/public/docs/cocalc-cli-862b8d4e.webp",
      "A terminal automating project docs, notebooks, and browser tasks",
    ),
    lastReviewed: "2026-05-24",
    slug: "cli/use-cocalc-cli",
    status: "ready",
    summary:
      "Use the CoCalc CLI for authenticated docs, browser, notebook, and project automation.",
    title: "Use the CoCalc CLI",
  },
  {
    audiences: ["agents", "researchers", "teams"],
    body: HTTP_API_BODY.trim(),
    category: "API",
    id: "api.http-api",
    image: docsIcon(
      "/public/docs/http-api-5067e8ed.webp",
      "A guarded HTTP API gateway with keys and connected endpoints",
    ),
    lastReviewed: "2026-05-24",
    slug: "api/http-api",
    status: "ready",
    summary:
      "Use the limited CoCalc HTTP API carefully, and prefer cocalc-cli for most automation.",
    title: "CoCalc HTTP API and API keys",
  },
  {
    actions: [
      {
        description: "Open a terminal in the active project.",
        executable: true,
        id: "project.terminal.open",
        label: "Open terminal",
        parameters: projectActionParameters(),
      },
    ],
    audiences: ["agents", "researchers", "students", "teams"],
    body: OPEN_TERMINAL_BODY.trim(),
    category: "Projects",
    id: "projects.open-terminal",
    image: docsIcon(
      "/public/docs/open-terminal-5c56d2b5.webp",
      "A project folder opening a durable terminal session",
    ),
    lastReviewed: "2026-05-24",
    slug: "projects/open-terminal",
    status: "ready",
    summary:
      "Use durable collaborative terminals backed by real project Linux processes.",
    title: "Open a terminal",
  },
  {
    audiences: ["agents", "researchers", "students", "teams"],
    body: USE_TERMINAL_BODY.trim(),
    category: "Terminal",
    id: "terminal.use-terminal",
    image: docsIcon(
      "/public/docs/terminal-56905fa2.webp",
      "Hand-drawn terminal opening project files",
    ),
    lastReviewed: "2026-05-25",
    slug: "terminal/use-terminal",
    status: "ready",
    summary:
      "Use persistent collaborative Linux shell sessions inside CoCalc projects.",
    title: "Use terminals",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: PROJECT_FILES_BODY.trim(),
    category: "Files",
    id: "files.project-files",
    image: docsIcon(
      "/public/docs/project-files-6c4ff552.webp",
      "A shared project folder with notebooks, scripts, data, and output",
    ),
    lastReviewed: "2026-05-24",
    slug: "files/project-files",
    status: "ready",
    summary:
      "Use the project filesystem as the shared place for notebooks, scripts, datasets, and output.",
    title: "Work with project files",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: FILE_EXPLORER_BODY.trim(),
    category: "Files",
    id: "files.explorer",
    image: docsIcon(
      "/public/docs/file-explorer-d0e7d92d.webp",
      "A project file browser with folders, file types, and search",
    ),
    lastReviewed: "2026-05-25",
    slug: "files/explorer",
    status: "ready",
    summary: "Create, open, upload, rename, move, and organize project files.",
    title: "Use the file explorer",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: MARKDOWN_BODY.trim(),
    category: "Files",
    id: "files.markdown",
    image: docsIcon(
      "/public/docs/markdown-dab5a1ac.webp",
      "A Markdown document with headings, checklists, and a code block",
    ),
    lastReviewed: "2026-05-25",
    slug: "files/markdown",
    status: "ready",
    summary:
      "Write README files, notes, instructions, math, code blocks, and collaborative documentation.",
    title: "Use Markdown",
  },
  {
    audiences: ["instructors", "researchers", "students", "teams"],
    body: SLIDES_BODY.trim(),
    category: "Files",
    id: "files.slides",
    image: docsIcon(
      "/public/docs/slides-84a00de7.webp",
      "Presentation slides with charts, images, and a projected screen",
    ),
    lastReviewed: "2026-05-25",
    slug: "files/slides",
    status: "ready",
    summary:
      "Create presentation slides that live with the project files they explain.",
    title: "Create slides",
  },
  {
    audiences: ["instructors", "researchers", "students", "teams"],
    body: WHITEBOARD_BODY.trim(),
    category: "Files",
    id: "files.whiteboard",
    image: docsIcon(
      "/public/docs/whiteboard-d2b02f98.webp",
      "A collaborative whiteboard with sticky notes, sketches, and arrows",
    ),
    lastReviewed: "2026-05-25",
    slug: "files/whiteboard",
    status: "ready",
    summary:
      "Sketch diagrams, lecture notes, and visual plans in a collaborative project file.",
    title: "Use whiteboards",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: PROJECT_LIST_BODY.trim(),
    category: "Projects",
    id: "projects.project-list",
    image: docsIcon(
      "/public/docs/create-project-5b221552.webp",
      "A projects page with recent work and a create-project control",
    ),
    lastReviewed: "2026-05-25",
    slug: "projects/project-list",
    status: "ready",
    summary:
      "Find, open, create, and organize the CoCalc projects you can access.",
    title: "Use the projects page",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: TASKS_BODY.trim(),
    category: "Projects",
    id: "projects.tasks",
    image: docsIcon(
      "/public/docs/tasks-07a6952f.webp",
      "A project task list with checked items, tags, and progress",
    ),
    lastReviewed: "2026-05-25",
    slug: "projects/tasks",
    status: "ready",
    summary:
      "Use task files for shared checklists, project plans, and durable TODO lists.",
    title: "Use task files",
  },
  {
    actions: [
      {
        description: "Create a Jupyter notebook in the active project.",
        executable: true,
        id: "project.jupyter.create",
        label: "Create notebook",
        parameters: projectActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "students"],
    body: CREATE_JUPYTER_BODY.trim(),
    category: "Jupyter",
    id: "jupyter.create-notebook",
    image: docsIcon(
      "/public/docs/create-jupyter-ddc9795c.webp",
      "A new Jupyter notebook with code cells and a kernel gear",
    ),
    lastReviewed: "2026-05-24",
    slug: "jupyter/create-notebook",
    status: "ready",
    summary:
      "Create notebooks that keep running and capturing output after browser disconnects.",
    title: "Create a Jupyter notebook",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: USE_JUPYTER_BODY.trim(),
    category: "Jupyter",
    id: "jupyter.use-jupyter",
    image: docsIcon(
      "/public/docs/use-jupyter-bcc9b49c.webp",
      "A collaborative Jupyter notebook with output and a running kernel",
    ),
    lastReviewed: "2026-05-24",
    slug: "jupyter/use-jupyter",
    status: "ready",
    summary:
      "Use collaborative durable Jupyter notebooks inside CoCalc projects.",
    title: "Use Jupyter notebooks",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: JUPYTER_KERNEL_TERMINATED_BODY.trim(),
    category: "Troubleshooting",
    id: "troubleshooting.jupyter-kernel-terminated",
    image: docsIcon(
      "/public/docs/memory-troubleshooting-7f40cd1d.webp",
      "A memory gauge warning about a stressed notebook kernel",
    ),
    lastReviewed: "2026-05-25",
    slug: "troubleshooting/jupyter-kernel-terminated",
    status: "ready",
    summary:
      "Recover from Jupyter kernels that crash, restart, or fail to start.",
    title: "Jupyter kernel terminated",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students"],
    body: CUSTOM_JUPYTER_KERNELS_BODY.trim(),
    category: "Jupyter",
    id: "jupyter.custom-kernels",
    image: docsIcon(
      "/public/docs/custom-jupyter-kernels-58a40bde.webp",
      "A custom Jupyter kernel connected to an isolated Python environment",
    ),
    lastReviewed: "2026-05-24",
    slug: "jupyter/custom-kernels",
    status: "ready",
    summary:
      "Create a custom Jupyter kernel backed by a uv-managed Python virtual environment.",
    title: "Custom Jupyter kernels with uv",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: PYTHON_BODY.trim(),
    category: "Python",
    id: "python.use-python",
    image: docsIcon(
      "/public/docs/python-93480a33.webp",
      "Python work across notebooks, scripts, terminals, and plots",
    ),
    lastReviewed: "2026-05-24",
    slug: "python/use-python",
    status: "ready",
    summary:
      "Use real Python through notebooks, scripts, terminals, virtual environments, and papers.",
    title: "Use Python in CoCalc",
  },
  {
    audiences: ["instructors", "researchers", "students", "teams"],
    body: LATEX_BODY.trim(),
    category: "LaTeX",
    id: "latex.build-papers",
    image: docsIcon(
      "/public/docs/latex-15ab38f8.webp",
      "A LaTeX paper with formulas, references, and a compiled PDF",
    ),
    lastReviewed: "2026-05-25",
    slug: "latex/build-papers",
    status: "ready",
    summary:
      "Write and build LaTeX papers, assignments, reports, figures, and bibliographies.",
    title: "Build LaTeX documents",
  },
  {
    audiences: ["instructors", "researchers", "students"],
    body: R_MARKDOWN_BODY.trim(),
    category: "R",
    id: "editors.r-markdown",
    image: docsIcon(
      "/public/docs/python-93480a33.webp",
      "A reproducible report combining prose, code chunks, plots, and output",
    ),
    lastReviewed: "2026-05-25",
    slug: "editors/r-markdown",
    status: "ready",
    summary:
      "Write reproducible R reports with Markdown prose, R chunks, plots, and rendered output.",
    title: "Use R Markdown",
  },
  {
    actions: [
      {
        description: "Open project Settings -> Environment -> Runtime Image.",
        executable: true,
        id: "settings.runtime.rootfs",
        label: "Open runtime image",
        parameters: projectActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: ROOTFS_BODY.trim(),
    category: "Projects",
    id: "projects.runtime-image",
    image: docsIcon(
      "/public/docs/runtime-image-09add8c9.webp",
      "A layered runtime image that defines a project's software stack",
    ),
    lastReviewed: "2026-05-24",
    slug: "projects/runtime-image",
    status: "ready",
    summary:
      "Choose, customize, and reuse the Linux software stack for a project.",
    title: "Runtime images and RootFS",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: MEMORY_TROUBLESHOOTING_BODY.trim(),
    category: "Troubleshooting",
    id: "troubleshooting.memory",
    image: docsIcon(
      "/public/docs/memory-troubleshooting-7f40cd1d.webp",
      "A memory gauge warning about a stressed notebook kernel",
    ),
    lastReviewed: "2026-05-24",
    slug: "troubleshooting/memory",
    status: "ready",
    summary:
      "Diagnose low-memory warnings, out-of-memory kills, and notebook kernel restarts.",
    title: "Low memory and out-of-memory crashes",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: CONNECTIVITY_TROUBLESHOOTING_BODY.trim(),
    category: "Troubleshooting",
    id: "troubleshooting.connectivity",
    image: docsIcon(
      "/public/docs/connectivity-eaca154f.webp",
      "A browser reconnecting to CoCalc services",
    ),
    lastReviewed: "2026-05-25",
    slug: "troubleshooting/connectivity",
    status: "ready",
    summary:
      "Diagnose sign-in, websocket, stale browser state, and network connection problems.",
    title: "Connectivity and browser troubleshooting",
  },
  {
    actions: [
      {
        description: "Open the top-level Project Hosts page.",
        executable: true,
        id: "hosts.open",
        label: "Open project hosts",
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOSTS_BODY.trim(),
    category: "Project hosts",
    id: "hosts.project-hosts",
    image: docsIcon(
      "/public/docs/project-hosts-684faa4c.webp",
      "A project host running several project folders",
    ),
    lastReviewed: "2026-05-24",
    slug: "hosts/project-hosts",
    status: "ready",
    summary:
      "Run projects on dedicated or cloud-backed compute for courses, research, and agent sandboxes.",
    title: "Use project hosts",
  },
  {
    actions: [
      {
        description: "Open a project host drawer on the Access tab.",
        executable: true,
        id: "hosts.access.open",
        label: "Open host access",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_ACCESS_BODY.trim(),
    category: "Project hosts",
    id: "hosts.access-and-ram",
    image: docsIcon(
      "/public/docs/project-hosts-access-ram-9245deeb.webp",
      "A project host access panel with delegated users and resource limits",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/access-and-ram",
    status: "ready",
    summary:
      "Delegate host access, understand shared-pool tiers, and set per-project RAM policy.",
    title: "Manage project host access and RAM",
  },
  {
    actions: [
      {
        description: "Open a project host drawer on the Projects tab.",
        executable: true,
        id: "hosts.move.open",
        label: "Open host projects",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_MOVE_BODY.trim(),
    category: "Project hosts",
    id: "hosts.move-projects",
    image: docsIcon(
      "/public/docs/project-hosts-move-47c2a6e8.webp",
      "A project folder moving between two project hosts across regions",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/move-projects",
    status: "ready",
    summary:
      "Move projects between hosts while accounting for backups, snapshots, region changes, and SSH.",
    title: "Move projects between hosts",
  },
  {
    actions: [
      {
        description: "Open a project host drawer.",
        executable: true,
        id: "hosts.lifecycle.open",
        label: "Open host lifecycle",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_LIFECYCLE_BODY.trim(),
    category: "Project hosts",
    id: "hosts.lifecycle",
    image: docsIcon(
      "/public/docs/project-hosts-lifecycle-6d603bd0.webp",
      "A project host with start stop restart deprovision and delete controls",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/lifecycle",
    status: "ready",
    summary:
      "Understand start, stop, restart, drain, deprovision, and delete actions for project hosts.",
    title: "Project host lifecycle actions",
  },
  {
    actions: [
      {
        description: "Open a project host drawer.",
        executable: true,
        id: "hosts.spot-recovery.open",
        label: "Open host details",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_SPOT_RECOVERY_BODY.trim(),
    category: "Project hosts",
    id: "hosts.spot-recovery",
    image: docsIcon(
      "/public/docs/project-hosts-spot-recovery-75af618c.webp",
      "A spot host recovering through retries and standard fallback",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/spot-recovery",
    status: "ready",
    summary:
      "Explain spot retry windows, standard fallback, probes, and returning from fallback to spot.",
    title: "Spot recovery strategy for project hosts",
  },
  {
    actions: [
      {
        description: "Open a project host drawer.",
        executable: true,
        id: "hosts.change-rules.open",
        label: "Open host details",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_CHANGE_RULES_BODY.trim(),
    category: "Project hosts",
    id: "hosts.change-rules",
    image: docsIcon(
      "/public/docs/project-hosts-change-rules-40b02147.webp",
      "Project host settings grouped by online change restart and deprovision",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/change-rules",
    status: "ready",
    summary:
      "Know which host edits are online, which require restart, and which require deprovision.",
    title: "What can change on a project host and when",
  },
  {
    actions: [
      {
        description: "Open a project host drawer on the Reliability tab.",
        executable: true,
        id: "hosts.reliability.open",
        label: "Open reliability",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_RELIABILITY_BODY.trim(),
    category: "Project hosts",
    id: "hosts.reliability",
    image: docsIcon(
      "/public/docs/project-hosts-reliability-e1f428a6.webp",
      "A project host with a reliability gauge and recent availability bars",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/reliability",
    status: "ready",
    summary:
      "Read host reliability, availability, outage exposure, planned downtime, and day-grid signals.",
    title: "Understand project host reliability",
  },
  {
    actions: [
      {
        description: "Open a project host drawer on the Runtime tab.",
        executable: true,
        id: "hosts.runtime.open",
        label: "Open runtime",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_SOFTWARE_LIFECYCLE_BODY.trim(),
    category: "Project hosts",
    id: "hosts.software-lifecycle",
    image: docsIcon(
      "/public/docs/project-hosts-software-lifecycle-29c58052.webp",
      "A project host with software packages daemon health and reconcile arrows",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/software-lifecycle",
    status: "ready",
    summary:
      "Understand runtime software, managed daemons, reconcile, upgrades, drift, and rollbacks.",
    title: "Project host software and daemon lifecycle",
  },
  {
    actions: [
      {
        description: "Open a project host drawer on the Storage tab.",
        executable: true,
        id: "hosts.storage.open",
        label: "Open storage",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_STORAGE_BODY.trim(),
    category: "Project hosts",
    id: "hosts.storage",
    image: docsIcon(
      "/public/docs/project-hosts-storage-cad76e1f.webp",
      "A project host with disks backups snapshots and protected project folders",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/storage",
    status: "ready",
    summary:
      "Understand host disk capacity, storage mode, backups, snapshots, and online disk growth.",
    title: "Project host storage, backups, and snapshots",
  },
  {
    actions: [
      {
        description: "Open a project host drawer on the Storage tab.",
        executable: true,
        id: "hosts.scratch.open",
        label: "Open scratch settings",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_SHARED_SCRATCH_BODY.trim(),
    category: "Project hosts",
    id: "hosts.shared-scratch",
    image: docsIcon(
      "/public/docs/project-hosts-shared-scratch-8409afa7.webp",
      "A host-scoped scratch disk shared by several project folders",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/shared-scratch",
    status: "ready",
    summary:
      "Use host-scoped /scratch storage without confusing it with project storage, backups, or moves.",
    title: "Shared scratch disks on project hosts",
  },
  {
    actions: [
      {
        description: "Open a project host drawer on the Logs tab.",
        executable: true,
        id: "hosts.logs.open",
        label: "Open logs",
        parameters: projectHostActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "teams"],
    body: PROJECT_HOST_LOGS_BODY.trim(),
    category: "Project hosts",
    id: "hosts.logs",
    image: docsIcon(
      "/public/docs/project-hosts-logs-df53d17e.webp",
      "A project host with logs diagnostics warnings and a magnifying glass",
    ),
    lastReviewed: "2026-05-27",
    slug: "hosts/logs",
    status: "ready",
    summary:
      "Use host logs with runtime and reliability state to debug provisioning, daemon, and provider issues.",
    title: "Debug project hosts with logs",
  },
  {
    actions: [
      {
        description: "Open project Settings -> People.",
        executable: true,
        id: "settings.people.collaborators",
        label: "Manage collaborators",
        parameters: projectActionParameters(),
      },
    ],
    audiences: ["instructors", "researchers", "students", "teams"],
    body: COLLABORATORS_BODY.trim(),
    category: "Projects",
    id: "projects.collaborators",
    image: docsIcon(
      "/public/docs/collaborators-8ce1955f.webp",
      "Collaborators sharing a project folder with realtime cursors",
    ),
    lastReviewed: "2026-05-24",
    slug: "projects/collaborators",
    status: "ready",
    summary:
      "Invite people into a shared project with realtime files, notebooks, terminals, and chat.",
    title: "Add project collaborators",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: CHAT_BODY.trim(),
    category: "Collaboration",
    id: "collaboration.chat",
    image: docsIcon(
      "/public/docs/collaborators-8ce1955f.webp",
      "A project chat conversation beside shared project files",
    ),
    lastReviewed: "2026-05-25",
    slug: "collaboration/chat",
    status: "ready",
    summary:
      "Discuss project work with collaborators and AI assistants in durable chat files.",
    title: "Use chat",
  },
  {
    audiences: ["instructors", "researchers", "students", "teams"],
    body: MENTIONS_BODY.trim(),
    category: "Collaboration",
    id: "collaboration.mentions",
    image: docsIcon(
      "/public/docs/collaborators-8ce1955f.webp",
      "A collaborator mention notification linked to project context",
    ),
    lastReviewed: "2026-05-25",
    slug: "collaboration/mentions",
    status: "ready",
    summary:
      "Notify collaborators with @mentions and return to the relevant project context.",
    title: "Use mentions",
  },
  {
    actions: [
      {
        description: "Open TimeTravel for the active file.",
        executable: true,
        id: "file.timetravel.open",
        label: "Open TimeTravel",
        parameters: projectActionParameters(),
      },
    ],
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: TIMETRAVEL_BODY.trim(),
    category: "Files",
    id: "files.timetravel",
    image: docsIcon(
      "/public/docs/timetravel-0f06290b.webp",
      "A TimeTravel timeline with Git revisions, snapshots, and restore points",
    ),
    lastReviewed: "2026-05-24",
    slug: "files/timetravel",
    status: "ready",
    summary: "Inspect, compare, and recover the history of files in a project.",
    title: "Use TimeTravel",
  },
  {
    audiences: ["agents", "researchers", "students", "teams"],
    body: GIT_BODY.trim(),
    category: "Files",
    id: "files.git",
    image: docsIcon(
      "/public/docs/git-a53df3e8.webp",
      "Git branch history beside project files",
    ),
    lastReviewed: "2026-05-24",
    slug: "files/git",
    status: "ready",
    summary:
      "Use Git for repository history alongside TimeTravel for file-focused recovery.",
    title: "Use Git",
  },
  {
    audiences: ["agents", "instructors"],
    body: COURSE_WORKFLOW_BODY.trim(),
    category: "Teaching",
    id: "teaching.course-workflow",
    image: docsIcon(
      "/public/docs/course-assignment-ede60e1a.webp",
      "Course assignments sent to student project folders",
    ),
    lastReviewed: "2026-05-25",
    slug: "teaching/course-workflow",
    status: "ready",
    summary:
      "Run computational courses with student projects, assignments, collection, grading, and feedback.",
    title: "Teach a course",
  },
  {
    actions: [
      {
        description: "Open course assignment creation.",
        executable: false,
        id: "course.assignment.create",
        label: "Create assignment",
      },
    ],
    audiences: ["agents", "instructors"],
    body: COURSE_ASSIGNMENT_BODY.trim(),
    category: "Teaching",
    id: "teaching.create-assignment",
    image: docsIcon(
      "/public/docs/course-assignment-ede60e1a.webp",
      "Course assignments sent to student project folders",
    ),
    lastReviewed: "2026-05-24",
    slug: "teaching/create-assignment",
    status: "ready",
    summary:
      "Assign, collect, grade, and return computational work in student projects.",
    title: "Create a course assignment",
  },
  {
    audiences: ["agents", "instructors"],
    body: NBGRADER_BODY.trim(),
    category: "Teaching",
    id: "teaching.nbgrader",
    image: docsIcon(
      "/public/docs/course-assignment-ede60e1a.webp",
      "Course assignments sent to student project folders",
    ),
    lastReviewed: "2026-05-25",
    slug: "teaching/nbgrader",
    status: "ready",
    summary:
      "Use nbgrader for structured Jupyter notebook grading in CoCalc courses.",
    title: "Use nbgrader",
  },
  {
    actions: [
      {
        description: "Open Codex chat in the active project.",
        executable: true,
        id: "project.codex.open",
        label: "Open Codex",
        parameters: projectActionParameters(),
      },
    ],
    audiences: ["agents", "researchers", "students", "teams"],
    body: CODEX_CHAT_BODY.trim(),
    category: "AI",
    id: "ai.codex-chat",
    image: docsIcon(
      "/public/docs/codex-chat-3008e11e.webp",
      "Codex chat working with project files, terminals, and notebooks",
    ),
    lastReviewed: "2026-05-24",
    slug: "ai/codex-chat",
    status: "ready",
    summary:
      "Use Codex inside a durable project workspace with files, terminals, and notebooks.",
    title: "Open Codex chat",
  },
  {
    audiences: ["agents", "instructors", "researchers", "students", "teams"],
    body: DOCS_BROWSER_BODY.trim(),
    category: "Docs",
    id: "docs.browser",
    image: docsIcon(
      "/public/docs/docs-browser-74a65d58.webp",
      "A searchable docs browser beside a project folder",
    ),
    lastReviewed: "2026-05-24",
    slug: "documentation/browser",
    status: "ready",
    summary:
      "Search version-matched CoCalc-ai docs from the public site or inside a project.",
    title: "Use the docs browser",
  },
  {
    audiences: ["agents", "teams"],
    body: DOCS_ACTIONS_BODY.trim(),
    category: "Docs",
    id: "docs.executable-actions",
    image: docsIcon(
      "/public/docs/executable-docs-actions-195b983b.webp",
      "Docs actions launching settings, terminal, and notebook panels",
    ),
    lastReviewed: "2026-05-24",
    slug: "documentation/executable-actions",
    status: "ready",
    summary:
      "Use stable docs action ids to open the right UI from docs or Codex.",
    title: "Use executable docs actions",
  },
  {
    audiences: ["agents", "teams"],
    body: BROWSER_AUTOMATION_BODY.trim(),
    category: "Docs",
    id: "docs.browser-automation",
    image: docsIcon(
      "/public/docs/browser-automation-5dc255b9.webp",
      "Browser automation inspecting a project page with a checklist",
    ),
    lastReviewed: "2026-05-24",
    slug: "documentation/browser-automation",
    status: "ready",
    summary:
      "Use scoped browser-session automation to inspect UI and verify docs.",
    title: "Use browser-session automation",
  },
];
