#!/usr/bin/env bash
set -euo pipefail

CLUSTER_ID=""
SEED_BAY_ID=""
LOCAL_BAY_ID=""
BIND_HOST=""
PEER_HEALTH_PORT="9402"
PEER_HEALTH_PATH="/peer-health"
PEER_LOCAL_HEALTH_TIMEOUT="3"
SEED_CONAT_PORT="10300"
TOPOLOGY_EPOCH=""
BAYS=()

usage() {
  cat <<'EOF'
Usage: render-bay-topology-env.sh [options] --bay <bay-id>=<internal-ip>...

Render /etc/cocalc/bay-topology.env for a bay in a multibay cluster.

Required:
  --cluster <id>             cluster id, e.g. bella
  --seed-bay <bay-id>        seed bay id
  --local-bay <bay-id>       bay id this file is for
  --bay <id>=<internal-ip>   repeat for every bay in the cluster

Options:
  --bind-host <ip>           internal IP to bind peer-health on; defaults to
                             the local bay's internal IP from --bay
  --peer-health-port <n>     default: 9402
  --peer-health-path <path>  default: /peer-health
  --peer-local-health-timeout <s>
                             local bay-health timeout used inside peer-health
                             responses, default: 3
  --seed-conat-port <n>      seed hub-worker Conat fabric port, default: 10300
  --topology-epoch <value>   default: current unix timestamp
  -h, --help                 show this help

Example:
  render-bay-topology-env.sh \
    --cluster bella \
    --seed-bay bay-0 \
    --local-bay bay-1 \
    --bay bay-0=10.206.0.21 \
    --bay bay-1=10.206.0.22
EOF
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

shell_quote() {
  printf "'"
  printf '%s' "$1" | sed "s/'/'\\\\''/g"
  printf "'"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster)
      CLUSTER_ID="$2"
      shift 2
      ;;
    --seed-bay)
      SEED_BAY_ID="$2"
      shift 2
      ;;
    --local-bay)
      LOCAL_BAY_ID="$2"
      shift 2
      ;;
    --bind-host)
      BIND_HOST="$2"
      shift 2
      ;;
    --peer-health-port)
      PEER_HEALTH_PORT="$2"
      shift 2
      ;;
    --peer-health-path)
      PEER_HEALTH_PATH="$2"
      shift 2
      ;;
    --peer-local-health-timeout)
      PEER_LOCAL_HEALTH_TIMEOUT="$2"
      shift 2
      ;;
    --seed-conat-port)
      SEED_CONAT_PORT="$2"
      shift 2
      ;;
    --topology-epoch)
      TOPOLOGY_EPOCH="$2"
      shift 2
      ;;
    --bay)
      BAYS+=("$2")
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

[[ -n "$CLUSTER_ID" ]] || die "--cluster is required"
[[ -n "$SEED_BAY_ID" ]] || die "--seed-bay is required"
[[ -n "$LOCAL_BAY_ID" ]] || die "--local-bay is required"
[[ "${#BAYS[@]}" -ge 1 ]] || die "at least one --bay is required"
[[ "$PEER_HEALTH_PORT" =~ ^[0-9]+$ ]] || die "--peer-health-port must be an integer"
[[ "$PEER_LOCAL_HEALTH_TIMEOUT" =~ ^[0-9]+$ ]] || die "--peer-local-health-timeout must be an integer"
[[ "$SEED_CONAT_PORT" =~ ^[0-9]+$ ]] || die "--seed-conat-port must be an integer"
[[ "$PEER_HEALTH_PATH" == /* ]] || die "--peer-health-path must start with /"

if [[ -z "$TOPOLOGY_EPOCH" ]]; then
  TOPOLOGY_EPOCH="$(date +%s)"
fi

bay_ids=()
urls=()
local_internal_ip=""
seed_internal_ip=""

for entry in "${BAYS[@]}"; do
  if [[ "$entry" != *=* ]]; then
    die "--bay must be formatted as bay-id=internal-ip: ${entry}"
  fi
  bay_id="${entry%%=*}"
  internal_ip="${entry#*=}"
  [[ -n "$bay_id" && -n "$internal_ip" ]] || die "invalid --bay entry: ${entry}"
  bay_ids+=("$bay_id")
  urls+=("${bay_id}=http://${internal_ip}:${PEER_HEALTH_PORT}${PEER_HEALTH_PATH}")
  if [[ "$bay_id" == "$LOCAL_BAY_ID" ]]; then
    local_internal_ip="$internal_ip"
  fi
  if [[ "$bay_id" == "$SEED_BAY_ID" ]]; then
    seed_internal_ip="$internal_ip"
  fi
done

[[ -n "$local_internal_ip" ]] || die "--local-bay is not present in --bay entries: ${LOCAL_BAY_ID}"
[[ -n "$seed_internal_ip" ]] || die "--seed-bay is not present in --bay entries: ${SEED_BAY_ID}"
if [[ -z "$BIND_HOST" ]]; then
  BIND_HOST="$local_internal_ip"
fi

role="attached"
if [[ "$LOCAL_BAY_ID" == "$SEED_BAY_ID" ]]; then
  role="seed"
fi

bay_ids_csv="$(IFS=,; echo "${bay_ids[*]}")"
peer_urls="$(IFS=' '; echo "${urls[*]}")"

cat <<EOF
# Generated by render-bay-topology-env.sh.
# Install as /etc/cocalc/bay-topology.env.

COCALC_CLUSTER_ID=$(shell_quote "$CLUSTER_ID")
COCALC_CLUSTER_ROLE=$(shell_quote "$role")
COCALC_CLUSTER_SEED_BAY_ID=$(shell_quote "$SEED_BAY_ID")
COCALC_CLUSTER_BAY_IDS=$(shell_quote "$bay_ids_csv")
COCALC_CLUSTER_TOPOLOGY_EPOCH=$(shell_quote "$TOPOLOGY_EPOCH")
COCALC_CLUSTER_SEED_CONAT_SERVER=$(shell_quote "http://${seed_internal_ip}:${SEED_CONAT_PORT}")
COCALC_INTER_BAY_CONAT_SERVER=$(shell_quote "http://${seed_internal_ip}:${SEED_CONAT_PORT}")

COCALC_BAY_PEER_HEALTH_HOST=$(shell_quote "$BIND_HOST")
COCALC_BAY_PEER_HEALTH_PORT=$(shell_quote "$PEER_HEALTH_PORT")
COCALC_BAY_PEER_HEALTH_PATH=$(shell_quote "$PEER_HEALTH_PATH")
COCALC_BAY_PEER_HEALTH_TIMEOUT_S=5
COCALC_BAY_PEER_LOCAL_HEALTH_TIMEOUT_S=$(shell_quote "$PEER_LOCAL_HEALTH_TIMEOUT")

COCALC_CLUSTER_PEER_HEALTH_URLS=$(shell_quote "$peer_urls")
EOF
